/**
 * Comprehensive Master Data and Room Definitions for Studio Penta (Shibuya x3, Shinjuku x2)
 * Pure phone-booking studios with full equipment details and one-tap calling integration.
 */
import { Studio, RoomWithSlots, RoomEquipment, AvailabilitySlot } from '@/types/studio';
import pentaShinjukuJson from '@/data/penta-shinjuku-real.json';

export const PENTA_STUDIOS: Record<string, Studio> = {
  'shibuya-penta-city': {
    id: 'shibuya-penta-city',
    name: 'スタジオペンタ 渋谷シティサイド店',
    chainName: 'STUDIO PENTA',
    area: '渋谷',
    prefecture: '東京都',
    nearestStation: '渋谷駅 西口 徒歩3分',
    address: '東京都渋谷区桜丘町24-2 第3富士商事ビルB1F',
    tel: '03-3462-2811',
    bookingUrl: 'https://studiopenta.jp/rehearsal/city/',
    websiteUrl: 'https://studiopenta.jp/rehearsal/city/',
    businessHoursSummary: '10:00〜24:00 (電話受付のみ)',
    is24Hours: false,
    groupBookingRule: '2ヶ月前より電話にて受付（オンライン予約非対応）',
    groupBookingLeadMonths: 2,
    soloBookingRule: '前日営業開始（10:00）より電話にて受付開始',
    soloBookingLeadHours: 38,
  },
  'shibuya-penta-juke': {
    id: 'shibuya-penta-juke',
    name: 'スタジオペンタ 渋谷ジュークハウス店',
    chainName: 'STUDIO PENTA',
    area: '渋谷',
    prefecture: '東京都',
    nearestStation: '渋谷駅 西口 徒歩4分',
    address: '東京都渋谷区桜丘町15-17 登栄桜丘ビルB1F',
    tel: '03-3462-2815',
    bookingUrl: 'https://studiopenta.jp/rehearsal/juke/',
    websiteUrl: 'https://studiopenta.jp/rehearsal/juke/',
    businessHoursSummary: '10:00〜24:00 (電話受付のみ)',
    is24Hours: false,
    groupBookingRule: '2ヶ月前より電話にて受付（オンライン予約非対応）',
    groupBookingLeadMonths: 2,
    soloBookingRule: '前日営業開始（10:00）より電話にて受付開始',
    soloBookingLeadHours: 38,
  },
  'shinjuku-penta-main': {
    id: 'shinjuku-penta-main',
    name: 'スタジオペンタ 新宿店',
    chainName: 'STUDIO PENTA',
    area: '新宿',
    prefecture: '東京都',
    nearestStation: '新宿駅 東口 徒歩3分 / 新宿三丁目駅 徒歩2分',
    address: '東京都新宿区新宿3-11-6 エビスビルB1F',
    tel: '03-3351-3140',
    bookingUrl: 'https://studiopenta.jp/rehearsal/shinjuku/',
    websiteUrl: 'https://studiopenta.jp/rehearsal/shinjuku/',
    businessHoursSummary: '10:00〜24:00 (土日祝は空き状況Web公開中 / 平日は電話受付)',
    is24Hours: false,
    groupBookingRule: '土日祝空き状況公開中 / 予約は電話にて受付',
    groupBookingLeadMonths: 2,
    soloBookingRule: '前日営業開始（10:00）より電話にて受付開始',
    soloBookingLeadHours: 38,
  },
  'ikebukuro-penta-main': {
    id: 'ikebukuro-penta-main',
    name: 'スタジオペンタ池袋店',
    chainName: 'STUDIO PENTA',
    area: '池袋',
    prefecture: '東京都',
    nearestStation: 'JR池袋駅 東口 徒歩5分',
    address: '東京都豊島区南池袋2-47-8',
    tel: '03-3981-5540',
    bookingUrl: 'https://studiopenta.jp/rehearsal/ikebukuro/',
    websiteUrl: 'https://studiopenta.jp/rehearsal/ikebukuro/',
    businessHoursSummary: '10:00〜24:00 (電話受付のみ)',
    is24Hours: false,
    groupBookingRule: '電話または店頭にて受付（オンライン予約非対応）',
    groupBookingLeadMonths: 2,
    soloBookingRule: '前日営業開始（10:00）より電話にて受付開始',
    soloBookingLeadHours: 38,
  },
  'ikebukuro-penta-hands': {
    id: 'ikebukuro-penta-hands',
    name: 'スタジオペンタ池袋ハンズサイド',
    chainName: 'STUDIO PENTA',
    area: '池袋',
    prefecture: '東京都',
    nearestStation: 'JR池袋駅 東口 徒歩5分',
    address: '東京都豊島区東池袋1-26-4',
    tel: '03-3981-4436',
    bookingUrl: 'https://studiopenta.jp/rehearsal/hands/',
    websiteUrl: 'https://studiopenta.jp/rehearsal/hands/',
    businessHoursSummary: '10:00〜24:00 (電話/LINE受付のみ)',
    is24Hours: false,
    groupBookingRule: '電話・LINE・店頭にて受付（オンライン予約非対応）',
    groupBookingLeadMonths: 2,
    soloBookingRule: '前日営業開始（10:00）より電話にて受付開始',
    soloBookingLeadHours: 38,
  },
};

interface PentaRoomDef {
  id: string;
  studioKey: string;
  name: string;
  floor?: string;
  tatami: number;
  capacity: number;
  priceRegular: number;
  priceDaytime: number;
  priceSolo: number;
  hasRecording: boolean;
  guitarAmps: string[];
  bassAmp: string;
  drumSet: string;
  paSystem: string;
  keyboards?: string[];
  notes?: string;
}

const PENTA_ROOMS_DEFINITIONS: PentaRoomDef[] = [
  // 1. 渋谷シティサイド (7室)
  {
    id: 'penta-city-1st',
    studioKey: 'shibuya-penta-city',
    name: '1st (16帖)',
    tatami: 16,
    capacity: 7,
    priceRegular: 3520,
    priceDaytime: 2530,
    priceSolo: 880,
    hasRecording: true,
    guitarAmps: ['Roland JC-120', 'Marshall JCM2000 DSL100', 'Mesa/Boogie Dual Rectifier'],
    bassAmp: 'Ampeg SVT-3PRO + SVT-810E',
    drumSet: 'Pearl Masters Studio',
    paSystem: 'YAMAHA EMX5016CF',
    notes: 'シティサイド最大16帖スタジオ。ヴィンテージアンプも完備。',
  },
  {
    id: 'penta-city-2st',
    studioKey: 'shibuya-penta-city',
    name: '2st (14帖)',
    tatami: 14,
    capacity: 6,
    priceRegular: 3190,
    priceDaytime: 2200,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'Marshall JCM900 4100'],
    bassAmp: 'Hartke HA3500 + 410XL',
    drumSet: 'Pearl Session Custom',
    paSystem: 'YAMAHA EMX512SC',
  },
  {
    id: 'penta-city-3st',
    studioKey: 'shibuya-penta-city',
    name: '3st (12帖)',
    tatami: 12,
    capacity: 5,
    priceRegular: 2860,
    priceDaytime: 1980,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'Marshall DSL100H'],
    bassAmp: 'Ampeg SVT-350',
    drumSet: 'TAMA Starclassic',
    paSystem: 'YAMAHA EMX512SC',
  },
  {
    id: 'penta-city-4st',
    studioKey: 'shibuya-penta-city',
    name: '4st (10帖)',
    tatami: 10,
    capacity: 5,
    priceRegular: 2640,
    priceDaytime: 1760,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'Marshall DSL40CR'],
    bassAmp: 'Hartke HA2500',
    drumSet: 'Pearl Export',
    paSystem: 'YAMAHA EMX212S',
  },
  {
    id: 'penta-city-5st',
    studioKey: 'shibuya-penta-city',
    name: '5st (9帖)',
    tatami: 9,
    capacity: 4,
    priceRegular: 2420,
    priceDaytime: 1650,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'Marshall DSL20HR'],
    bassAmp: 'Hartke HA2500',
    drumSet: 'Pearl Export',
    paSystem: 'YAMAHA EMX212S',
  },
  {
    id: 'penta-city-6st',
    studioKey: 'shibuya-penta-city',
    name: '6st (8帖)',
    tatami: 8,
    capacity: 4,
    priceRegular: 2200,
    priceDaytime: 1540,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'Marshall JTM45'],
    bassAmp: 'Fender Bassman',
    drumSet: 'Canopus Yaiba',
    paSystem: 'YAMAHA StagePas',
  },
  {
    id: 'penta-city-7st',
    studioKey: 'shibuya-penta-city',
    name: '7st (7帖)',
    tatami: 7,
    capacity: 3,
    priceRegular: 1980,
    priceDaytime: 1430,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'VOX AC15'],
    bassAmp: 'Hartke HD150',
    drumSet: 'TAMA Club-JAM',
    paSystem: 'YAMAHA StagePas',
  },

  // 2. 渋谷ジュークハウス (7室)
  {
    id: 'penta-juke-1st',
    studioKey: 'shibuya-penta-juke',
    name: '1st (16帖)',
    tatami: 16,
    capacity: 7,
    priceRegular: 3520,
    priceDaytime: 2530,
    priceSolo: 880,
    hasRecording: true,
    guitarAmps: ['Roland JC-120', 'Marshall JCM2000 DSL100', 'Hughes & Kettner TriAmp'],
    bassAmp: 'Ampeg SVT-4PRO + 810E',
    drumSet: 'Pearl Masters Premium',
    paSystem: 'YAMAHA EMX5016CF',
    notes: 'ジュークハウスのフラッグシップ。抜けの良い音響設計。',
  },
  {
    id: 'penta-juke-2st',
    studioKey: 'shibuya-penta-juke',
    name: '2st (15帖)',
    tatami: 15,
    capacity: 6,
    priceRegular: 3300,
    priceDaytime: 2310,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'Marshall JCM900 4100'],
    bassAmp: 'Hartke HA3500 + 410XL',
    drumSet: 'TAMA Starclassic',
    paSystem: 'YAMAHA EMX512SC',
  },
  {
    id: 'penta-juke-3st',
    studioKey: 'shibuya-penta-juke',
    name: '3st (13帖)',
    tatami: 13,
    capacity: 6,
    priceRegular: 2970,
    priceDaytime: 2090,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'Marshall DSL100H'],
    bassAmp: 'Ampeg SVT-350',
    drumSet: 'Pearl Session Custom',
    paSystem: 'YAMAHA EMX512SC',
  },
  {
    id: 'penta-juke-4st',
    studioKey: 'shibuya-penta-juke',
    name: '4st (12帖)',
    tatami: 12,
    capacity: 5,
    priceRegular: 2860,
    priceDaytime: 1980,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'Marshall DSL40CR'],
    bassAmp: 'Hartke HA2500',
    drumSet: 'Pearl Export',
    paSystem: 'YAMAHA EMX212S',
  },
  {
    id: 'penta-juke-5st',
    studioKey: 'shibuya-penta-juke',
    name: '5st (10帖)',
    tatami: 10,
    capacity: 5,
    priceRegular: 2640,
    priceDaytime: 1760,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'Marshall DSL20HR'],
    bassAmp: 'Hartke HA2500',
    drumSet: 'Pearl Export',
    paSystem: 'YAMAHA EMX212S',
  },
  {
    id: 'penta-juke-6st',
    studioKey: 'shibuya-penta-juke',
    name: '6st (8帖)',
    tatami: 8,
    capacity: 4,
    priceRegular: 2200,
    priceDaytime: 1540,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'Fender Blues Junior'],
    bassAmp: 'Hartke HD150',
    drumSet: 'TAMA Club-JAM',
    paSystem: 'YAMAHA StagePas',
  },
  {
    id: 'penta-juke-7st',
    studioKey: 'shibuya-penta-juke',
    name: '7st (7帖)',
    tatami: 7,
    capacity: 3,
    priceRegular: 1980,
    priceDaytime: 1430,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'VOX AC15'],
    bassAmp: 'Hartke HD150',
    drumSet: 'TAMA Club-JAM',
    paSystem: 'YAMAHA StagePas',
  },

  // 4. 新宿店 (全19部屋を完全網羅・土日祝日リアルタイム空き枠連携)
  {
    id: 'penta-shinjuku-101',
    studioKey: 'shinjuku-penta-main',
    name: '101st L (16帖)',
    floor: '1F',
    tatami: 16,
    capacity: 7,
    priceRegular: 3520,
    priceDaytime: 2530,
    priceSolo: 880,
    hasRecording: true,
    guitarAmps: ['Roland JC-120', 'Marshall JCM2000 DSL100', 'Mesa/Boogie Dual Rectifier'],
    bassAmp: 'Ampeg SVT-4PRO + SVT-810E',
    drumSet: 'TAMA Starclassic Performer',
    paSystem: 'YAMAHA EMX5016CF',
    notes: 'ペンタ新宿店1階の大型フラッグシップスタジオ。セルフレコ対応。',
  },
  {
    id: 'penta-shinjuku-102',
    studioKey: 'shinjuku-penta-main',
    name: '102st L (16帖)',
    floor: '1F',
    tatami: 16,
    capacity: 7,
    priceRegular: 3520,
    priceDaytime: 2530,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'Marshall JCM900 4100'],
    bassAmp: 'Ampeg SVT-350 + 410XL',
    drumSet: 'Pearl Masters Studio',
    paSystem: 'YAMAHA EMX5016CF',
  },
  {
    id: 'penta-shinjuku-103',
    studioKey: 'shinjuku-penta-main',
    name: '103st L (16帖)',
    floor: '1F',
    tatami: 16,
    capacity: 7,
    priceRegular: 3520,
    priceDaytime: 2530,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'Marshall JVM210H'],
    bassAmp: 'Hartke HA3500 + 410XL',
    drumSet: 'Canopus Yaiba II',
    paSystem: 'YAMAHA EMX5016CF',
  },
  {
    id: 'penta-shinjuku-201',
    studioKey: 'shinjuku-penta-main',
    name: '201st M (14帖)',
    floor: '2F',
    tatami: 14,
    capacity: 6,
    priceRegular: 3190,
    priceDaytime: 2200,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'Marshall JCM900 4100'],
    bassAmp: 'Hartke HA3500',
    drumSet: 'Pearl Session Custom',
    paSystem: 'YAMAHA EMX512SC',
  },
  {
    id: 'penta-shinjuku-202',
    studioKey: 'shinjuku-penta-main',
    name: '202st M (14帖)',
    floor: '2F',
    tatami: 14,
    capacity: 6,
    priceRegular: 3190,
    priceDaytime: 2200,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'Marshall DSL100H'],
    bassAmp: 'Ampeg SVT-350',
    drumSet: 'TAMA Starclassic',
    paSystem: 'YAMAHA EMX512SC',
  },
  {
    id: 'penta-shinjuku-203',
    studioKey: 'shinjuku-penta-main',
    name: '203st M (14帖)',
    floor: '2F',
    tatami: 14,
    capacity: 6,
    priceRegular: 3190,
    priceDaytime: 2200,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'Marshall JCM900 4100'],
    bassAmp: 'Hartke HA3500',
    drumSet: 'Pearl Session Custom',
    paSystem: 'YAMAHA EMX512SC',
  },
  {
    id: 'penta-shinjuku-204',
    studioKey: 'shinjuku-penta-main',
    name: '204st M (14帖)',
    floor: '2F',
    tatami: 14,
    capacity: 6,
    priceRegular: 3190,
    priceDaytime: 2200,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'Marshall DSL100H'],
    bassAmp: 'Ampeg SVT-350',
    drumSet: 'TAMA Starclassic',
    paSystem: 'YAMAHA EMX512SC',
  },
  {
    id: 'penta-shinjuku-301',
    studioKey: 'shinjuku-penta-main',
    name: '301st M (14帖)',
    floor: '3F',
    tatami: 14,
    capacity: 6,
    priceRegular: 3190,
    priceDaytime: 2200,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'Marshall JCM900 4100'],
    bassAmp: 'Hartke HA3500',
    drumSet: 'Pearl Session Custom',
    paSystem: 'YAMAHA EMX512SC',
  },
  {
    id: 'penta-shinjuku-302',
    studioKey: 'shinjuku-penta-main',
    name: '302st M (12帖)',
    floor: '3F',
    tatami: 12,
    capacity: 5,
    priceRegular: 2860,
    priceDaytime: 1980,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'Marshall DSL40CR'],
    bassAmp: 'Hartke HA2500',
    drumSet: 'Pearl Export',
    paSystem: 'YAMAHA EMX212S',
  },
  {
    id: 'penta-shinjuku-303',
    studioKey: 'shinjuku-penta-main',
    name: '303st M (12帖)',
    floor: '3F',
    tatami: 12,
    capacity: 5,
    priceRegular: 2860,
    priceDaytime: 1980,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'Marshall DSL40CR'],
    bassAmp: 'Hartke HA2500',
    drumSet: 'Pearl Export',
    paSystem: 'YAMAHA EMX212S',
  },
  {
    id: 'penta-shinjuku-304',
    studioKey: 'shinjuku-penta-main',
    name: '304st M (12帖)',
    floor: '3F',
    tatami: 12,
    capacity: 5,
    priceRegular: 2860,
    priceDaytime: 1980,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'Marshall DSL40CR'],
    bassAmp: 'Hartke HA2500',
    drumSet: 'Pearl Export',
    paSystem: 'YAMAHA EMX212S',
  },
  {
    id: 'penta-shinjuku-401',
    studioKey: 'shinjuku-penta-main',
    name: '401st M (12帖)',
    floor: '4F',
    tatami: 12,
    capacity: 5,
    priceRegular: 2860,
    priceDaytime: 1980,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'Marshall DSL40CR'],
    bassAmp: 'Hartke HA2500',
    drumSet: 'Pearl Export',
    paSystem: 'YAMAHA EMX212S',
  },
  {
    id: 'penta-shinjuku-402',
    studioKey: 'shinjuku-penta-main',
    name: '402st M (10帖)',
    floor: '4F',
    tatami: 10,
    capacity: 5,
    priceRegular: 2640,
    priceDaytime: 1760,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'Marshall DSL20HR'],
    bassAmp: 'Hartke HA2500',
    drumSet: 'Pearl Export',
    paSystem: 'YAMAHA EMX212S',
  },
  {
    id: 'penta-shinjuku-403',
    studioKey: 'shinjuku-penta-main',
    name: '403st M (10帖)',
    floor: '4F',
    tatami: 10,
    capacity: 5,
    priceRegular: 2640,
    priceDaytime: 1760,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'Marshall DSL20HR'],
    bassAmp: 'Hartke HA2500',
    drumSet: 'Pearl Export',
    paSystem: 'YAMAHA EMX212S',
  },
  {
    id: 'penta-shinjuku-404',
    studioKey: 'shinjuku-penta-main',
    name: '404st M (10帖)',
    floor: '4F',
    tatami: 10,
    capacity: 5,
    priceRegular: 2640,
    priceDaytime: 1760,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'Marshall DSL20HR'],
    bassAmp: 'Hartke HA2500',
    drumSet: 'Pearl Export',
    paSystem: 'YAMAHA EMX212S',
  },
  {
    id: 'penta-shinjuku-501',
    studioKey: 'shinjuku-penta-main',
    name: '501st M (12帖)',
    floor: '5F',
    tatami: 12,
    capacity: 5,
    priceRegular: 2860,
    priceDaytime: 1980,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'Marshall DSL40CR'],
    bassAmp: 'Hartke HA2500',
    drumSet: 'Pearl Export',
    paSystem: 'YAMAHA EMX212S',
  },
  {
    id: 'penta-shinjuku-502',
    studioKey: 'shinjuku-penta-main',
    name: '502st M (10帖)',
    floor: '5F',
    tatami: 10,
    capacity: 5,
    priceRegular: 2640,
    priceDaytime: 1760,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'Marshall DSL20HR'],
    bassAmp: 'Hartke HA2500',
    drumSet: 'Pearl Export',
    paSystem: 'YAMAHA EMX212S',
  },
  {
    id: 'penta-shinjuku-503',
    studioKey: 'shinjuku-penta-main',
    name: '503st M (10帖)',
    floor: '5F',
    tatami: 10,
    capacity: 5,
    priceRegular: 2640,
    priceDaytime: 1760,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'Marshall DSL20HR'],
    bassAmp: 'Hartke HA2500',
    drumSet: 'Pearl Export',
    paSystem: 'YAMAHA EMX212S',
  },
  {
    id: 'penta-shinjuku-504',
    studioKey: 'shinjuku-penta-main',
    name: '504st L (16帖)',
    floor: '5F',
    tatami: 16,
    capacity: 7,
    priceRegular: 3520,
    priceDaytime: 2530,
    priceSolo: 880,
    hasRecording: true,
    guitarAmps: ['Roland JC-120', 'Marshall JVM210H', 'Fender Twin Reverb'],
    bassAmp: 'Ampeg SVT-4PRO',
    drumSet: 'Canopus Yaiba II',
    paSystem: 'YAMAHA EMX5016CF',
    notes: '5階の大型スタジオ。Fender Twin Reverb完備。セルフレコ対応。',
  },

  // 5. 池袋店 (5室・電話予約のみ)
  {
    id: 'penta-ikebukuro-1st',
    studioKey: 'ikebukuro-penta-main',
    name: '1st SMALL (9帖)',
    tatami: 9,
    capacity: 4,
    priceRegular: 2500,
    priceDaytime: 1700,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Marshall JVM210H+1960A', 'Roland JC-120', 'Fender Twin Reverb'],
    bassAmp: 'Ampeg B2-RE + SVT610HLF',
    drumSet: 'Pearl MX',
    paSystem: 'YAMAHA EMX512SC',
  },
  {
    id: 'penta-ikebukuro-2st',
    studioKey: 'ikebukuro-penta-main',
    name: '2st SMALL (9帖)',
    tatami: 9,
    capacity: 4,
    priceRegular: 2500,
    priceDaytime: 1700,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Marshall JVM210H+1960A', 'Roland JC-120', 'Fender Twin Reverb'],
    bassAmp: 'Ampeg B2-RE + SVT610HLF',
    drumSet: 'Pearl Masters Maple',
    paSystem: 'YAMAHA EMX512SC',
  },
  {
    id: 'penta-ikebukuro-3st',
    studioKey: 'ikebukuro-penta-main',
    name: '3st LARGE (12帖)',
    tatami: 12,
    capacity: 5,
    priceRegular: 2650,
    priceDaytime: 1900,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Marshall JVM210H+1960A', 'Mesa/Boogie Dual Rectifier', 'Roland JC-120'],
    bassAmp: 'Ampeg SVT-450H + SVT610HLF',
    drumSet: 'Pearl MRX',
    paSystem: 'YAMAHA EMX5016CF',
  },
  {
    id: 'penta-ikebukuro-4st',
    studioKey: 'ikebukuro-penta-main',
    name: '4st LARGE (12帖)',
    tatami: 12,
    capacity: 5,
    priceRegular: 2650,
    priceDaytime: 1900,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Marshall JVM210H+1960A', 'Mesa/Boogie Dual Rectifier', 'Roland JC-120'],
    bassAmp: 'Ampeg SVT-450H + SVT610HLF',
    drumSet: 'Pearl CM',
    paSystem: 'YAMAHA EMX5016CF',
  },
  {
    id: 'penta-ikebukuro-5st',
    studioKey: 'ikebukuro-penta-main',
    name: '5st LARGE (12帖)',
    tatami: 12,
    capacity: 5,
    priceRegular: 2650,
    priceDaytime: 1900,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Marshall JVM210H+1960A', 'Mesa/Boogie Dual Rectifier', 'Roland JC-120'],
    bassAmp: 'Ampeg SVT-450H + SVT610HLF',
    drumSet: 'Pearl MRX',
    paSystem: 'YAMAHA EMX5016CF',
    notes: '池袋エリアで最も歴史のあるリハーサルスタジオ。',
  },

  // 6. 池袋ハンズサイド (8室・電話/LINE予約のみ)
  {
    id: 'penta-hands-1st',
    studioKey: 'ikebukuro-penta-hands',
    name: '#1 SMALL (11帖)',
    tatami: 11,
    capacity: 5,
    priceRegular: 2420,
    priceDaytime: 1650,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'VOX AC30C2-TV-BC'],
    bassAmp: 'EDEN Terra Nova TN501 + Ampeg SVT-410HE/SVT-15EN',
    drumSet: 'Canopus NV60-M1',
    paSystem: 'YAMAHA EMX512SC',
  },
  {
    id: 'penta-hands-2st',
    studioKey: 'ikebukuro-penta-hands',
    name: '#2 LARGE (20帖)',
    tatami: 20,
    capacity: 8,
    priceRegular: 3630,
    priceDaytime: 2750,
    priceSolo: 880,
    hasRecording: true,
    guitarAmps: ['Marshall JVM210H', 'Mesa/Boogie Dual Rectifier', 'Roland JC-120'],
    bassAmp: 'Ampeg SVT-450H + SVT-810E',
    drumSet: 'Canopus R.F.M.',
    paSystem: 'YAMAHA EMX5016CF',
    notes: 'ハンズサイド最大の20帖フラッグシップスタジオ。',
  },
  {
    id: 'penta-hands-3st',
    studioKey: 'ikebukuro-penta-hands',
    name: '#3 MEDIUM (14帖)',
    tatami: 14,
    capacity: 6,
    priceRegular: 2750,
    priceDaytime: 2090,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Marshall JVM210H', 'Roland JC-120'],
    bassAmp: 'Ampeg SVT-3PRO + SVT-810E',
    drumSet: 'Pearl Masters Premium',
    paSystem: 'YAMAHA EMX512SC',
  },
  {
    id: 'penta-hands-4st',
    studioKey: 'ikebukuro-penta-hands',
    name: '#4 MEDIUM (14帖)',
    tatami: 14,
    capacity: 6,
    priceRegular: 2750,
    priceDaytime: 2090,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['LINE 6 Spider Valve HD100', 'Roland JC-120'],
    bassAmp: 'Aguilar TONE HAMMER 500 + SVT-810E',
    drumSet: 'YAMAHA Recording Custom',
    paSystem: 'YAMAHA EMX512SC',
  },
  {
    id: 'penta-hands-5st',
    studioKey: 'ikebukuro-penta-hands',
    name: '#5 MEDIUM (14帖)',
    tatami: 14,
    capacity: 6,
    priceRegular: 2750,
    priceDaytime: 2090,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Marshall JVM210H', 'Roland JC-120'],
    bassAmp: 'Ampeg SVT-3PRO + SVT-810E',
    drumSet: 'Pearl Masters Premium',
    paSystem: 'YAMAHA EMX512SC',
  },
  {
    id: 'penta-hands-6st',
    studioKey: 'ikebukuro-penta-hands',
    name: '#6 SMALL (11帖)',
    tatami: 11,
    capacity: 5,
    priceRegular: 2420,
    priceDaytime: 1650,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'Blackstar Series One 100'],
    bassAmp: 'Ampeg B-2RE',
    drumSet: 'Pearl Masters Premium',
    paSystem: 'YAMAHA EMX512SC',
  },
  {
    id: 'penta-hands-7st',
    studioKey: 'ikebukuro-penta-hands',
    name: '#7 MEDIUM Plus (15帖)',
    tatami: 15,
    capacity: 6,
    priceRegular: 3190,
    priceDaytime: 2420,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Marshall JCM2000', 'Roland JC-120'],
    bassAmp: 'Ampeg SVT-7PRO / SVT-AV + SVT-810E',
    drumSet: 'Pearl Masters Premium',
    paSystem: 'YAMAHA EMX5016CF',
  },
  {
    id: 'penta-hands-8st',
    studioKey: 'ikebukuro-penta-hands',
    name: '#8 MEDIUM (14帖)',
    tatami: 14,
    capacity: 6,
    priceRegular: 2750,
    priceDaytime: 2090,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'Marshall JVM210H'],
    bassAmp: 'Ampeg SVT-3PRO + SVT-810E',
    drumSet: 'YAMAHA Recording Custom',
    paSystem: 'YAMAHA EMX512SC',
  },
];

export function getPentaRealRooms(targetDateStr: string): RoomWithSlots[] {
  let order = 500;

  // 新宿店のクローリング済みリアルタイムスロットマップを作成
  const shinjukuRoomsMap = new Map<string, any>();
  if (pentaShinjukuJson?.rooms && Array.isArray(pentaShinjukuJson.rooms)) {
    for (const r of pentaShinjukuJson.rooms) {
      shinjukuRoomsMap.set(r.id, r);
    }
  }

  return PENTA_ROOMS_DEFINITIONS.map((def) => {
    const studio = PENTA_STUDIOS[def.studioKey];
    const isShinjuku = def.studioKey === 'shinjuku-penta-main';

    let slots: AvailabilitySlot[] = [];
    if (isShinjuku) {
      const crawled = shinjukuRoomsMap.get(def.id);
      if (crawled?.slots) {
        slots = crawled.slots
          .filter((s: any) => s.start_time.startsWith(targetDateStr))
          .map((s: any) => ({
            id: s.id,
            roomId: def.id,
            startTime: s.start_time,
            endTime: s.end_time,
            status: s.status === 'AVAILABLE' ? 'available' : 'booked',
          }));
      }
    }

    const equipment: RoomEquipment = {
      id: `eq-${def.id}`,
      roomId: def.id,
      guitarAmps: def.guitarAmps,
      bassAmp: def.bassAmp,
      drumSet: def.drumSet,
      isTwinPedalAllowed: true,
      paSystem: def.paSystem,
      keyboards: def.keyboards,
      additionalNotes: `${def.notes || 'スタジオペンタ正規常設機材。'}${
        isShinjuku
          ? `※土日祝日は空き状況をWeb公開中（平日またはご予約はお電話：${studio.tel}）。`
          : `※電話予約店舗のため、空き確認・ご予約はお電話（${studio.tel}）にて承ります。`
      }`,
    };

    return {
      id: def.id,
      studioId: studio.id,
      name: def.name,
      floor: def.floor || 'B1F',
      sizeTatami: def.tatami,
      capacity: def.capacity,
      pricePerHourRegular: def.priceRegular,
      pricePerHourDaytime: def.priceDaytime,
      pricePerHourSolo: def.priceSolo,
      hasMirror: true,
      hasRecording: def.hasRecording,
      startTimeOffset: 0,
      orderIndex: order++,
      studio,
      equipment,
      slots,
    };
  });
}

