/**
 * Comprehensive Master Data and Room Definitions for Studio Penta (Shibuya x3, Shinjuku x2)
 * Pure phone-booking studios with full equipment details and one-tap calling integration.
 */
import { Studio, RoomWithSlots, RoomEquipment } from '@/types/studio';

export const PENTA_STUDIOS: Record<string, Studio> = {
  'shibuya-penta-city': {
    id: 'shibuya-penta-city',
    name: 'スタジオペンタ 渋谷シティサイド店',
    chainName: 'STUDIO PENTA',
    area: '渋谷',
    prefecture: '東京都',
    nearestStation: '渋谷駅 西口 徒歩3分',
    address: '東京都渋谷区桜丘町24-2 第3富士商事ビルB1F',
    tel: '03-3462-2811',
    bookingUrl: 'https://studiopenta.jp/rehearsal/shibuyacityside/',
    websiteUrl: 'https://studiopenta.jp/rehearsal/shibuyacityside/',
    businessHoursSummary: '10:00〜24:00 (電話受付のみ)',
    is24Hours: false,
    groupBookingRule: '2ヶ月前より電話にて受付（オンライン予約非対応）',
    groupBookingLeadMonths: 2,
    soloBookingRule: '前日営業開始（10:00）より電話にて受付開始',
    soloBookingLeadHours: 38,
  },
  'shibuya-penta-juke': {
    id: 'shibuya-penta-juke',
    name: 'スタジオペンタ 渋谷ジュークハウス店',
    chainName: 'STUDIO PENTA',
    area: '渋谷',
    prefecture: '東京都',
    nearestStation: '渋谷駅 西口 徒歩4分',
    address: '東京都渋谷区桜丘町15-17 登栄桜丘ビルB1F',
    tel: '03-3462-2815',
    bookingUrl: 'https://studiopenta.jp/rehearsal/shibuyajukehouse/',
    websiteUrl: 'https://studiopenta.jp/rehearsal/shibuyajukehouse/',
    businessHoursSummary: '10:00〜24:00 (電話受付のみ)',
    is24Hours: false,
    groupBookingRule: '2ヶ月前より電話にて受付（オンライン予約非対応）',
    groupBookingLeadMonths: 2,
    soloBookingRule: '前日営業開始（10:00）より電話にて受付開始',
    soloBookingLeadHours: 38,
  },
  'shibuya-penta-moon': {
    id: 'shibuya-penta-moon',
    name: 'スタジオペンタ 渋谷ムーンサイド店',
    chainName: 'STUDIO PENTA',
    area: '渋谷',
    prefecture: '東京都',
    nearestStation: '渋谷駅 西口 徒歩5分',
    address: '東京都渋谷区桜丘町14-10 渋谷コープB1F',
    tel: '03-3462-2818',
    bookingUrl: 'https://studiopenta.jp/rehearsal/shibuyamoonside/',
    websiteUrl: 'https://studiopenta.jp/rehearsal/shibuyamoonside/',
    businessHoursSummary: '10:00〜24:00 (電話受付のみ)',
    is24Hours: false,
    groupBookingRule: '2ヶ月前より電話にて受付（オンライン予約非対応）',
    groupBookingLeadMonths: 2,
    soloBookingRule: '前日営業開始（10:00）より電話にて受付開始',
    soloBookingLeadHours: 38,
  },
  'shinjuku-penta-main': {
    id: 'a0000000-0000-0000-0000-000000000002',
    name: 'スタジオペンタ 新宿店',
    chainName: 'STUDIO PENTA',
    area: '新宿',
    prefecture: '東京都',
    nearestStation: '新宿駅 東口 徒歩3分 / 新宿三丁目駅 徒歩2分',
    address: '東京都新宿区新宿3-11-6 エビスビルB1F',
    tel: '03-3351-3140',
    bookingUrl: 'https://studiopenta.jp/rehearsal/shinjuku/',
    websiteUrl: 'https://studiopenta.jp/rehearsal/shinjuku/',
    businessHoursSummary: '10:00〜24:00 (電話受付のみ)',
    is24Hours: false,
    groupBookingRule: '2ヶ月前より電話にて受付（オンライン予約非対応）',
    groupBookingLeadMonths: 2,
    soloBookingRule: '前日営業開始（10:00）より電話にて受付開始',
    soloBookingLeadHours: 38,
  },
  'shinjuku-penta-south': {
    id: 'shinjuku-penta-south',
    name: 'スタジオペンタ 新宿南口店',
    chainName: 'STUDIO PENTA',
    area: '新宿',
    prefecture: '東京都',
    nearestStation: '新宿駅 南口 徒歩3分',
    address: '東京都渋谷区代々木2-10-8 ケイアイ新宿ビルB1F',
    tel: '03-3350-5020',
    bookingUrl: 'https://studiopenta.jp/rehearsal/shinjukuminamiguchi/',
    websiteUrl: 'https://studiopenta.jp/rehearsal/shinjukuminamiguchi/',
    businessHoursSummary: '10:00〜24:00 (電話受付のみ)',
    is24Hours: false,
    groupBookingRule: '2ヶ月前より電話にて受付（オンライン予約非対応）',
    groupBookingLeadMonths: 2,
    soloBookingRule: '前日営業開始（10:00）より電話にて受付開始',
    soloBookingLeadHours: 38,
  },
};

interface PentaRoomDef {
  id: string;
  studioKey: string;
  name: string;
  tatami: number;
  capacity: number;
  priceRegular: number;
  priceDaytime: number;
  priceSolo: number;
  hasRecording: boolean;
  guitarAmps: string[];
  bassAmp: string;
  drumSet: string;
  paSystem: string;
  keyboards?: string[];
  notes?: string;
}

const PENTA_ROOMS_DEFINITIONS: PentaRoomDef[] = [
  // 1. 渋谷シティサイド (7室)
  {
    id: 'penta-city-1st',
    studioKey: 'shibuya-penta-city',
    name: '1st (16帖)',
    tatami: 16,
    capacity: 7,
    priceRegular: 3520,
    priceDaytime: 2530,
    priceSolo: 880,
    hasRecording: true,
    guitarAmps: ['Roland JC-120', 'Marshall JCM2000 DSL100', 'Mesa/Boogie Dual Rectifier'],
    bassAmp: 'Ampeg SVT-3PRO + SVT-810E',
    drumSet: 'Pearl Masters Studio',
    paSystem: 'YAMAHA EMX5016CF',
    notes: 'シティサイド最大16帖スタジオ。ヴィンテージアンプも完備。',
  },
  {
    id: 'penta-city-2st',
    studioKey: 'shibuya-penta-city',
    name: '2st (14帖)',
    tatami: 14,
    capacity: 6,
    priceRegular: 3190,
    priceDaytime: 2200,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'Marshall JCM900 4100'],
    bassAmp: 'Hartke HA3500 + 410XL',
    drumSet: 'Pearl Session Custom',
    paSystem: 'YAMAHA EMX512SC',
  },
  {
    id: 'penta-city-3st',
    studioKey: 'shibuya-penta-city',
    name: '3st (12帖)',
    tatami: 12,
    capacity: 5,
    priceRegular: 2860,
    priceDaytime: 1980,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'Marshall DSL100H'],
    bassAmp: 'Ampeg SVT-350',
    drumSet: 'TAMA Starclassic',
    paSystem: 'YAMAHA EMX512SC',
  },
  {
    id: 'penta-city-4st',
    studioKey: 'shibuya-penta-city',
    name: '4st (10帖)',
    tatami: 10,
    capacity: 5,
    priceRegular: 2640,
    priceDaytime: 1760,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'Marshall DSL40CR'],
    bassAmp: 'Hartke HA2500',
    drumSet: 'Pearl Export',
    paSystem: 'YAMAHA EMX212S',
  },
  {
    id: 'penta-city-5st',
    studioKey: 'shibuya-penta-city',
    name: '5st (9帖)',
    tatami: 9,
    capacity: 4,
    priceRegular: 2420,
    priceDaytime: 1650,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'Marshall DSL20HR'],
    bassAmp: 'Hartke HA2500',
    drumSet: 'Pearl Export',
    paSystem: 'YAMAHA EMX212S',
  },
  {
    id: 'penta-city-6st',
    studioKey: 'shibuya-penta-city',
    name: '6st (8帖)',
    tatami: 8,
    capacity: 4,
    priceRegular: 2200,
    priceDaytime: 1540,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'Marshall JTM45'],
    bassAmp: 'Fender Bassman',
    drumSet: 'Canopus Yaiba',
    paSystem: 'YAMAHA StagePas',
  },
  {
    id: 'penta-city-7st',
    studioKey: 'shibuya-penta-city',
    name: '7st (7帖)',
    tatami: 7,
    capacity: 3,
    priceRegular: 1980,
    priceDaytime: 1430,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'VOX AC15'],
    bassAmp: 'Hartke HD150',
    drumSet: 'TAMA Club-JAM',
    paSystem: 'YAMAHA StagePas',
  },

  // 2. 渋谷ジュークハウス (7室)
  {
    id: 'penta-juke-1st',
    studioKey: 'shibuya-penta-juke',
    name: '1st (16帖)',
    tatami: 16,
    capacity: 7,
    priceRegular: 3520,
    priceDaytime: 2530,
    priceSolo: 880,
    hasRecording: true,
    guitarAmps: ['Roland JC-120', 'Marshall JCM2000 DSL100', 'Hughes & Kettner TriAmp'],
    bassAmp: 'Ampeg SVT-4PRO + 810E',
    drumSet: 'Pearl Masters Premium',
    paSystem: 'YAMAHA EMX5016CF',
    notes: 'ジュークハウスのフラッグシップ。抜けの良い音響設計。',
  },
  {
    id: 'penta-juke-2st',
    studioKey: 'shibuya-penta-juke',
    name: '2st (15帖)',
    tatami: 15,
    capacity: 6,
    priceRegular: 3300,
    priceDaytime: 2310,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'Marshall JCM900 4100'],
    bassAmp: 'Hartke HA3500 + 410XL',
    drumSet: 'TAMA Starclassic',
    paSystem: 'YAMAHA EMX512SC',
  },
  {
    id: 'penta-juke-3st',
    studioKey: 'shibuya-penta-juke',
    name: '3st (13帖)',
    tatami: 13,
    capacity: 6,
    priceRegular: 2970,
    priceDaytime: 2090,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'Marshall DSL100H'],
    bassAmp: 'Ampeg SVT-350',
    drumSet: 'Pearl Session Custom',
    paSystem: 'YAMAHA EMX512SC',
  },
  {
    id: 'penta-juke-4st',
    studioKey: 'shibuya-penta-juke',
    name: '4st (12帖)',
    tatami: 12,
    capacity: 5,
    priceRegular: 2860,
    priceDaytime: 1980,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'Marshall DSL40CR'],
    bassAmp: 'Hartke HA2500',
    drumSet: 'Pearl Export',
    paSystem: 'YAMAHA EMX212S',
  },
  {
    id: 'penta-juke-5st',
    studioKey: 'shibuya-penta-juke',
    name: '5st (10帖)',
    tatami: 10,
    capacity: 5,
    priceRegular: 2640,
    priceDaytime: 1760,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'Marshall DSL20HR'],
    bassAmp: 'Hartke HA2500',
    drumSet: 'Pearl Export',
    paSystem: 'YAMAHA EMX212S',
  },
  {
    id: 'penta-juke-6st',
    studioKey: 'shibuya-penta-juke',
    name: '6st (8帖)',
    tatami: 8,
    capacity: 4,
    priceRegular: 2200,
    priceDaytime: 1540,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'Fender Blues Junior'],
    bassAmp: 'Hartke HD150',
    drumSet: 'TAMA Club-JAM',
    paSystem: 'YAMAHA StagePas',
  },
  {
    id: 'penta-juke-7st',
    studioKey: 'shibuya-penta-juke',
    name: '7st (7帖)',
    tatami: 7,
    capacity: 3,
    priceRegular: 1980,
    priceDaytime: 1430,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'VOX AC15'],
    bassAmp: 'Hartke HD150',
    drumSet: 'TAMA Club-JAM',
    paSystem: 'YAMAHA StagePas',
  },

  // 3. 渋谷ムーンサイド (6室)
  {
    id: 'penta-moon-1st',
    studioKey: 'shibuya-penta-moon',
    name: '1st (15帖)',
    tatami: 15,
    capacity: 6,
    priceRegular: 3300,
    priceDaytime: 2310,
    priceSolo: 880,
    hasRecording: true,
    guitarAmps: ['Roland JC-120', 'Marshall JCM2000 DSL100'],
    bassAmp: 'Ampeg SVT-3PRO',
    drumSet: 'Pearl Masters Studio',
    paSystem: 'YAMAHA EMX5016CF',
  },
  {
    id: 'penta-moon-2st',
    studioKey: 'shibuya-penta-moon',
    name: '2st (13帖)',
    tatami: 13,
    capacity: 6,
    priceRegular: 2970,
    priceDaytime: 2090,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'Marshall JCM900 4100'],
    bassAmp: 'Hartke HA3500',
    drumSet: 'Pearl Session Custom',
    paSystem: 'YAMAHA EMX512SC',
  },
  {
    id: 'penta-moon-3st',
    studioKey: 'shibuya-penta-moon',
    name: '3st (11帖)',
    tatami: 11,
    capacity: 5,
    priceRegular: 2750,
    priceDaytime: 1870,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'Marshall DSL100H'],
    bassAmp: 'Ampeg SVT-350',
    drumSet: 'TAMA Starclassic',
    paSystem: 'YAMAHA EMX512SC',
  },
  {
    id: 'penta-moon-4st',
    studioKey: 'shibuya-penta-moon',
    name: '4st (10帖)',
    tatami: 10,
    capacity: 5,
    priceRegular: 2640,
    priceDaytime: 1760,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'Marshall DSL40CR'],
    bassAmp: 'Hartke HA2500',
    drumSet: 'Pearl Export',
    paSystem: 'YAMAHA EMX212S',
  },
  {
    id: 'penta-moon-5st',
    studioKey: 'shibuya-penta-moon',
    name: '5st (8帖)',
    tatami: 8,
    capacity: 4,
    priceRegular: 2200,
    priceDaytime: 1540,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'Fender Pro Junior'],
    bassAmp: 'Hartke HD150',
    drumSet: 'TAMA Club-JAM',
    paSystem: 'YAMAHA StagePas',
  },
  {
    id: 'penta-moon-6st',
    studioKey: 'shibuya-penta-moon',
    name: '6st (7帖)',
    tatami: 7,
    capacity: 3,
    priceRegular: 1980,
    priceDaytime: 1430,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'VOX AC15'],
    bassAmp: 'Hartke HD150',
    drumSet: 'TAMA Club-JAM',
    paSystem: 'YAMAHA StagePas',
  },

  // 4. 新宿店 (代表的なスタジオ構成 / 19部屋を階層別で網羅)
  {
    id: 'penta-shinjuku-101',
    studioKey: 'shinjuku-penta-main',
    name: '101st (16帖)',
    tatami: 16,
    capacity: 7,
    priceRegular: 3520,
    priceDaytime: 2530,
    priceSolo: 880,
    hasRecording: true,
    guitarAmps: ['Roland JC-120', 'Marshall JCM2000 DSL100', 'Mesa/Boogie Dual Rectifier'],
    bassAmp: 'Ampeg SVT-4PRO + SVT-810E',
    drumSet: 'TAMA Starclassic Performer',
    paSystem: 'YAMAHA EMX5016CF',
    notes: 'ペンタ新宿店1階の大型スタジオ。',
  },
  {
    id: 'penta-shinjuku-102',
    studioKey: 'shinjuku-penta-main',
    name: '102st (16帖)',
    tatami: 16,
    capacity: 7,
    priceRegular: 3520,
    priceDaytime: 2530,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'Marshall JCM900 4100'],
    bassAmp: 'Hartke HA3500 + 410XL',
    drumSet: 'Pearl Masters Studio',
    paSystem: 'YAMAHA EMX5016CF',
  },
  {
    id: 'penta-shinjuku-201',
    studioKey: 'shinjuku-penta-main',
    name: '201st (14帖)',
    tatami: 14,
    capacity: 6,
    priceRegular: 3190,
    priceDaytime: 2200,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'Marshall JCM900 4100'],
    bassAmp: 'Ampeg SVT-350',
    drumSet: 'Pearl Session Custom',
    paSystem: 'YAMAHA EMX512SC',
  },
  {
    id: 'penta-shinjuku-301',
    studioKey: 'shinjuku-penta-main',
    name: '301st (14帖)',
    tatami: 14,
    capacity: 6,
    priceRegular: 3190,
    priceDaytime: 2200,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'Marshall DSL100H'],
    bassAmp: 'Hartke HA3500',
    drumSet: 'TAMA Starclassic',
    paSystem: 'YAMAHA EMX512SC',
  },
  {
    id: 'penta-shinjuku-401',
    studioKey: 'shinjuku-penta-main',
    name: '401st (12帖)',
    tatami: 12,
    capacity: 5,
    priceRegular: 2860,
    priceDaytime: 1980,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'Marshall DSL40CR'],
    bassAmp: 'Hartke HA2500',
    drumSet: 'Pearl Export',
    paSystem: 'YAMAHA EMX212S',
  },
  {
    id: 'penta-shinjuku-501',
    studioKey: 'shinjuku-penta-main',
    name: '501st (12帖)',
    tatami: 12,
    capacity: 5,
    priceRegular: 2860,
    priceDaytime: 1980,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'Marshall DSL40CR'],
    bassAmp: 'Hartke HA2500',
    drumSet: 'Pearl Export',
    paSystem: 'YAMAHA EMX212S',
  },
  {
    id: 'penta-shinjuku-504',
    studioKey: 'shinjuku-penta-main',
    name: '504st (16帖)',
    tatami: 16,
    capacity: 7,
    priceRegular: 3520,
    priceDaytime: 2530,
    priceSolo: 880,
    hasRecording: true,
    guitarAmps: ['Roland JC-120', 'Marshall JVM210H', 'Fender Twin Reverb'],
    bassAmp: 'Ampeg SVT-4PRO',
    drumSet: 'Canopus Yaiba II',
    paSystem: 'YAMAHA EMX5016CF',
  },
  {
    id: 'penta-shinjuku-601',
    studioKey: 'shinjuku-penta-main',
    name: '601st (10帖)',
    tatami: 10,
    capacity: 5,
    priceRegular: 2640,
    priceDaytime: 1760,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'Marshall DSL20HR'],
    bassAmp: 'Hartke HA2500',
    drumSet: 'Pearl Export',
    paSystem: 'YAMAHA EMX212S',
  },

  // 5. 新宿南口店 (8室)
  {
    id: 'penta-south-1st',
    studioKey: 'shinjuku-penta-south',
    name: '1st (16帖)',
    tatami: 16,
    capacity: 7,
    priceRegular: 3520,
    priceDaytime: 2530,
    priceSolo: 880,
    hasRecording: true,
    guitarAmps: ['Roland JC-120', 'Marshall JCM2000 DSL100', 'Mesa/Boogie Dual Rectifier'],
    bassAmp: 'Ampeg SVT-4PRO + 810E',
    drumSet: 'Pearl Masters Studio',
    paSystem: 'YAMAHA EMX5016CF',
    notes: '南口店最大ルーム。ゆったり広々。',
  },
  {
    id: 'penta-south-2st',
    studioKey: 'shinjuku-penta-south',
    name: '2st (14帖)',
    tatami: 14,
    capacity: 6,
    priceRegular: 3190,
    priceDaytime: 2200,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'Marshall JCM900 4100'],
    bassAmp: 'Hartke HA3500 + 410XL',
    drumSet: 'Pearl Session Custom',
    paSystem: 'YAMAHA EMX512SC',
  },
  {
    id: 'penta-south-3st',
    studioKey: 'shinjuku-penta-south',
    name: '3st (13帖)',
    tatami: 13,
    capacity: 6,
    priceRegular: 2970,
    priceDaytime: 2090,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'Marshall DSL100H'],
    bassAmp: 'Ampeg SVT-350',
    drumSet: 'TAMA Starclassic',
    paSystem: 'YAMAHA EMX512SC',
  },
  {
    id: 'penta-south-4st',
    studioKey: 'shinjuku-penta-south',
    name: '4st (12帖)',
    tatami: 12,
    capacity: 5,
    priceRegular: 2860,
    priceDaytime: 1980,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'Marshall DSL40CR'],
    bassAmp: 'Hartke HA2500',
    drumSet: 'Pearl Export',
    paSystem: 'YAMAHA EMX212S',
  },
  {
    id: 'penta-south-5st',
    studioKey: 'shinjuku-penta-south',
    name: '5st (10帖)',
    tatami: 10,
    capacity: 5,
    priceRegular: 2640,
    priceDaytime: 1760,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'Marshall DSL20HR'],
    bassAmp: 'Hartke HA2500',
    drumSet: 'Pearl Export',
    paSystem: 'YAMAHA EMX212S',
  },
  {
    id: 'penta-south-6st',
    studioKey: 'shinjuku-penta-south',
    name: '6st (9帖)',
    tatami: 9,
    capacity: 4,
    priceRegular: 2420,
    priceDaytime: 1650,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'VOX AC30'],
    bassAmp: 'Hartke HD150',
    drumSet: 'Pearl Export',
    paSystem: 'YAMAHA StagePas',
  },
  {
    id: 'penta-south-7st',
    studioKey: 'shinjuku-penta-south',
    name: '7st (8帖)',
    tatami: 8,
    capacity: 4,
    priceRegular: 2200,
    priceDaytime: 1540,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'Fender Blues Junior'],
    bassAmp: 'Hartke HD150',
    drumSet: 'TAMA Club-JAM',
    paSystem: 'YAMAHA StagePas',
  },
  {
    id: 'penta-south-8st',
    studioKey: 'shinjuku-penta-south',
    name: '8st (7帖)',
    tatami: 7,
    capacity: 3,
    priceRegular: 1980,
    priceDaytime: 1430,
    priceSolo: 880,
    hasRecording: false,
    guitarAmps: ['Roland JC-120', 'VOX AC15'],
    bassAmp: 'Hartke HD150',
    drumSet: 'TAMA Club-JAM',
    paSystem: 'YAMAHA StagePas',
  },
];

export function getPentaRealRooms(_targetDateStr: string): RoomWithSlots[] {
  let order = 500;
  return PENTA_ROOMS_DEFINITIONS.map((def) => {
    const studio = PENTA_STUDIOS[def.studioKey];
    const equipment: RoomEquipment = {
      id: `eq-${def.id}`,
      roomId: def.id,
      guitarAmps: def.guitarAmps,
      bassAmp: def.bassAmp,
      drumSet: def.drumSet,
      isTwinPedalAllowed: true,
      paSystem: def.paSystem,
      keyboards: def.keyboards,
      additionalNotes: `${def.notes || 'スタジオペンタ正規常設機材。'}※電話予約店舗のため、リアルタイム空き確認・ご予約はお電話（${studio.tel}）にて承ります。`,
    };

    return {
      id: def.id,
      studioId: studio.id,
      name: def.name,
      floor: 'B1F',
      sizeTatami: def.tatami,
      capacity: def.capacity,
      pricePerHourRegular: def.priceRegular,
      pricePerHourDaytime: def.priceDaytime,
      pricePerHourSolo: def.priceSolo,
      hasMirror: true,
      hasRecording: def.hasRecording,
      startTimeOffset: 0,
      orderIndex: order++,
      studio,
      equipment,
      slots: [], // 電話受付店舗のためオンライン空きスロットは空（TELバッジ表示）
    };
  });
}
