import { TEMP_HIDDEN_STUDIO_NAMES } from './hidden-studios';

export interface SupportedStudio {
  id: string;
  name: string;
  chainName: string;
  area: '渋谷' | '新宿' | '秋葉原・上野' | '高田馬場' | '池袋' | '下北沢' | '吉祥寺' | '高円寺' | '船橋' | '横浜' | '亀戸・小岩' | '松戸・柏' | '町田';
  nearestStation: string;
  address: string;
  roomCount: number;
  syncType: 'web_api' | 'web_calendar' | 'phone';
  syncLabel: string;
  systemName: string;
  is24Hours: boolean;
  businessHours: string;
  tel: string;
  websiteUrl: string;
  features: string[];
}

const ALL_SUPPORTED_STUDIOS: SupportedStudio[] = [
  // -------------------------------------------------------------
  // 渋谷エリア (7店舗 / 計81部屋)
  // ※スタジオペンタ渋谷ムーンサイド店は2025年4月29日閉店のため掲載終了
  // -------------------------------------------------------------
  {
    id: 'shibuya-noah-honten',
    name: 'サウンドスタジオノア 渋谷本店',
    chainName: 'SOUND STUDIO NOAH',
    area: '渋谷',
    nearestStation: '渋谷駅 ハチ公口 徒歩6分 / 神泉駅 徒歩8分',
    address: '東京都渋谷区宇田川町36-0 ビルディングB1F-4F',
    roomCount: 14,
    syncType: 'web_api',
    syncLabel: 'Web空き状況',
    systemName: 'ノア公式API連携',
    is24Hours: true,
    businessHours: '24時間営業',
    tel: '03-5485-1441',
    websiteUrl: 'https://www.studionoah.jp/shibuya/',
    features: ['24時間営業', '大型リハ対応', '個人練習Web受付', 'セルフレコブース'],
  },
  {
    id: 'shibuya-noah-1',
    name: 'サウンドスタジオノア 渋谷1号店',
    chainName: 'SOUND STUDIO NOAH',
    area: '渋谷',
    nearestStation: '渋谷駅 東口・宮益坂 徒歩3分',
    address: '東京都渋谷区渋谷2-19-15 宮益坂ビルディングB1F',
    roomCount: 12,
    syncType: 'web_api',
    syncLabel: 'Web空き状況',
    systemName: 'ノア公式API連携',
    is24Hours: true,
    businessHours: '24時間営業',
    tel: '03-5485-1441',
    websiteUrl: 'https://www.studionoah.jp/shibuya1/',
    features: ['24時間営業', '駅チカ徒歩3分', '個人練習Web受付', 'JC-120/Marshall全室'],
  },
  {
    id: 'shibuya-noah-2',
    name: 'サウンドスタジオノア 渋谷2号店',
    chainName: 'SOUND STUDIO NOAH',
    area: '渋谷',
    nearestStation: '渋谷駅 ハチ公口 徒歩5分 / 井の頭通り沿い',
    address: '東京都渋谷区宇田川町39-2 B1F',
    roomCount: 14,
    syncType: 'web_api',
    syncLabel: 'Web空き状況',
    systemName: 'ノア公式API連携',
    is24Hours: true,
    businessHours: '24時間営業 (朝モーニング枠あり)',
    tel: '03-3780-5766',
    websiteUrl: 'https://www.studionoah.jp/shibuya2/',
    features: ['24時間営業', '朝割モーニング枠', '30分開始枠併用', '広々ロビー'],
  },
  {
    id: 'shibuya-noah-3',
    name: 'サウンドスタジオノア 渋谷3号店',
    chainName: 'SOUND STUDIO NOAH',
    area: '渋谷',
    nearestStation: '渋谷駅 西口・マークシティ口 徒歩5分',
    address: '東京都渋谷区道玄坂1-15-3 プリメーラ道玄坂B1F',
    roomCount: 15,
    syncType: 'web_api',
    syncLabel: 'Web空き状況',
    systemName: 'ノア公式API連携',
    is24Hours: true,
    businessHours: '24時間営業',
    tel: '03-6416-3663',
    websiteUrl: 'https://www.studionoah.jp/shibuya3/',
    features: ['24時間営業', '道玄坂エリア', '個人練習Web受付', '高音質PA'],
  },
  {
    id: 'shibuya-gateway-01',
    name: 'ゲートウェイスタジオ 渋谷道玄坂店',
    chainName: 'GATEWAY STUDIO',
    area: '渋谷',
    nearestStation: '渋谷駅 道玄坂口 徒歩4分',
    address: '東京都渋谷区道玄坂2-16-7 花菱ビル3F-5F',
    roomCount: 12,
    syncType: 'web_calendar',
    syncLabel: 'Web空き状況',
    systemName: 'Reserve1.jp (自動巡回)',
    is24Hours: false,
    businessHours: '10:00〜23:00',
    tel: '03-3462-5552',
    websiteUrl: 'http://www.gw-studio.com/studios/studio_shibu2/',
    features: ['00分/30分開始混在', '個人練習770円/h', '28帖ゲネプロスタジオ'],
  },
  {
    id: 'shibuya-penta-city',
    name: 'スタジオペンタ 渋谷シティサイド店',
    chainName: 'STUDIO PENTA',
    area: '渋谷',
    nearestStation: '渋谷駅 西口・桜丘町 徒歩3分',
    address: '東京都渋谷区桜丘町24-2 第3富士商事ビルB1F',
    roomCount: 7,
    syncType: 'phone',
    syncLabel: '電話予約スタジオ',
    systemName: 'ワンタップ電話受付 (tel:)',
    is24Hours: false,
    businessHours: '10:00〜24:00',
    tel: '03-3462-2811',
    websiteUrl: 'https://studiopenta.jp/rehearsal/city/',
    features: ['桜丘町徒歩3分', 'ワンタップ電話予約', '個人練習前日10時〜', 'ビンテージアンプ常設'],
  },
  {
    id: 'shibuya-penta-juke',
    name: 'スタジオペンタ 渋谷ジュークハウス店',
    chainName: 'STUDIO PENTA',
    area: '渋谷',
    nearestStation: '渋谷駅 西口 徒歩4分',
    address: '東京都渋谷区桜丘町15-17 登栄桜丘ビルB1F',
    roomCount: 7,
    syncType: 'phone',
    syncLabel: '電話予約スタジオ',
    systemName: 'ワンタップ電話受付 (tel:)',
    is24Hours: false,
    businessHours: '10:00〜24:00',
    tel: '03-3462-2815',
    websiteUrl: 'https://studiopenta.jp/rehearsal/juke/',
    features: ['西口徒歩4分', 'ワンタップ電話予約', '個人練習前日10時〜', '名物スタッフ常駐'],
  },
  // -------------------------------------------------------------
  // 新宿エリア (8店舗 / 計79部屋)
  // -------------------------------------------------------------
  {
    id: 'shinjuku-noah',
    name: 'サウンドスタジオノア 新宿店',
    chainName: 'SOUND STUDIO NOAH',
    area: '新宿',
    nearestStation: '新宿駅 西口 徒歩4分 / 新宿西口駅 徒歩3分',
    address: '東京都新宿区西新宿1-3-14 新宿サンゲンビル1F-7F',
    roomCount: 21,
    syncType: 'web_api',
    syncLabel: 'Web空き状況',
    systemName: 'ノア公式API連携',
    is24Hours: true,
    businessHours: '24時間営業',
    tel: '03-5332-8366',
    websiteUrl: 'https://www.studionoah.jp/shinjuku/',
    features: ['都内最大級21部屋', '24時間営業', '西口大ガードすぐ', 'グランドピアノ室完備'],
  },
  {
    id: 'shinjuku-node',
    name: 'STUDIO NODE 新宿店',
    chainName: 'STUDIO NODE',
    area: '新宿',
    nearestStation: '新宿駅 西口 徒歩6分 / 西武新宿駅 徒歩3分',
    address: '東京都新宿区西新宿7-16-12 YSビルB1F',
    roomCount: 7,
    syncType: 'web_calendar',
    syncLabel: 'Web空き状況',
    systemName: 'studio-node.jp (自動巡回)',
    is24Hours: false,
    businessHours: '10:00〜24:00',
    tel: '03-5386-3371',
    websiteUrl: 'https://www.studio-node.com/HomeSH.html',
    features: ['西新宿エリア', '00分/30分開始混在', 'Web予約即時完結', '手頃な料金設定', 'ドラム設備充実'],
  },
  {
    id: 'shinjuku-penta-main',
    name: 'スタジオペンタ 新宿店',
    chainName: 'STUDIO PENTA',
    area: '新宿',
    nearestStation: '新宿駅 東口 徒歩3分 / 新宿三丁目駅 徒歩2分',
    address: '東京都新宿区新宿3-11-6 エビスビルB1F',
    roomCount: 19,
    syncType: 'web_calendar',
    syncLabel: '土日祝Web / 平日電話',
    systemName: 'ペンタ新宿 空き室ボード連携',
    is24Hours: false,
    businessHours: '10:00〜24:00',
    tel: '03-3351-3140',
    websiteUrl: 'https://studiopenta.jp/rehearsal/shinjuku/',
    features: ['新宿東口屈指の19部屋', '土日祝Web空き状況公開', '平日ワンタップ電話予約', '個人練習前日10時〜'],
  },
  {
    id: 'ongakukan-shinjuku-west',
    name: 'スタジオ音楽館 新宿西口店',
    chainName: 'スタジオ音楽館',
    area: '新宿',
    nearestStation: '新宿駅 西口 徒歩2分 / 新宿西口駅 徒歩3分',
    address: '東京都新宿区西新宿7-15-4 YSビルB2F',
    roomCount: 7,
    syncType: 'web_calendar',
    syncLabel: 'Web空き状況',
    systemName: 'ajg.jp (自動巡回)',
    is24Hours: false,
    businessHours: '10:00〜24:00 (予約に応じ24時間営業対応)',
    tel: '03-3368-0131',
    websiteUrl: 'http://www.st-ongakukan.com/sinjukunishi/sinjukunishi.html',
    features: ['西新宿駅近徒歩2分', '全室00分スタート', 'Web即時空き状況確認', '個人練習前日21時〜', '格安料金体系'],
  },
  {
    id: 'museum-shinjuku',
    name: 'スタジオミュージアム新宿店',
    chainName: 'スタジオミュージアム',
    area: '新宿',
    nearestStation: 'JR新宿駅 南口 徒歩5分',
    address: '東京都渋谷区代々木2-19-5',
    roomCount: 9,
    syncType: 'web_calendar',
    syncLabel: 'Web空き状況',
    systemName: 'studi-ol.com (自動巡回)',
    is24Hours: false,
    businessHours: '9:00〜24:00',
    tel: '03-3373-8200',
    websiteUrl: 'https://studio-museum.com/',
    features: ['新宿南口徒歩5分', '9畳〜12畳の計9部屋', '00分/30分開始混在', 'Web即時空き状況確認'],
  },
  {
    id: 'hillvalley-studio',
    name: 'ヒルバレースタジオ',
    chainName: 'HILL VALLEY STUDIO',
    area: '新宿',
    nearestStation: '新宿三丁目駅 E1出口 徒歩1分',
    address: '東京都新宿区新宿5-18-20 ルックハイツB1',
    roomCount: 3,
    syncType: 'web_calendar',
    syncLabel: 'Web空き状況',
    systemName: 'studi-ol.com (自動巡回)',
    is24Hours: false,
    businessHours: '平日12:00〜23:30 / 土日祝10:00〜23:30',
    tel: '03-6302-1718',
    websiteUrl: 'https://hillvalleystudio.net/',
    features: ['新宿三丁目駅徒歩1分', 'ライブハウスANTIKNOCKプロデュース', 'Web即時空き状況確認', 'レコーディング対応'],
  },
  {
    id: 'vantage-studio',
    name: 'Sound Studio Vantage',
    chainName: 'Sound Studio Vantage',
    area: '新宿',
    nearestStation: 'JR大久保駅 南口 徒歩3分',
    address: '東京都新宿区百人町1-23-4 D-SQUARE Shinjuku 8F',
    roomCount: 3,
    syncType: 'web_calendar',
    syncLabel: 'Web空き状況',
    systemName: 'studi-ol.com (自動巡回)',
    is24Hours: false,
    businessHours: '平日10:00〜23:00 / 土日祝9:00〜24:00',
    tel: '03-5989-1877',
    websiteUrl: 'http://www.studiovantage.jp/',
    features: ['大久保駅南口徒歩3分', '全3室の小規模スタジオ', 'Web即時空き状況確認', '豊富なドラムセット'],
  },
  {
    id: 'music-man-shinjuku',
    name: 'Music man サウンドスタジオ',
    chainName: 'Music man',
    area: '新宿',
    nearestStation: 'JR新宿駅 西口 徒歩4分',
    address: '東京都新宿区西新宿7-10-13 ガイアビル2F・3F',
    roomCount: 10,
    syncType: 'web_calendar',
    syncLabel: 'Web空き状況',
    systemName: 'Reserve1.jp (自動巡回)',
    is24Hours: false,
    businessHours: '9:30〜24:00（予約により深夜営業あり）',
    tel: '03-3367-2727',
    websiteUrl: 'https://www.music-man.jp/index.php',
    features: ['西口徒歩4分', '5タイプ×2フロアの計10部屋', '個人練習は全室一律料金', 'Web即時空き状況確認'],
  },

  // -------------------------------------------------------------
  // 秋葉原・上野エリア (9店舗 / 計69部屋)
  // -------------------------------------------------------------
  {
    id: 'akiba-noah',
    name: 'サウンドスタジオノア 秋葉原店',
    chainName: 'SOUND STUDIO NOAH',
    area: '秋葉原・上野',
    nearestStation: '末広町駅 徒歩1分 / 秋葉原駅 徒歩6分',
    address: '東京都千代田区外神田6-14-8',
    roomCount: 14,
    syncType: 'web_api',
    syncLabel: 'Web空き状況',
    systemName: 'ノア公式API連携',
    is24Hours: true,
    businessHours: '24時間営業',
    tel: '03-5816-8383',
    websiteUrl: 'https://www.studionoah.jp/akihabara/',
    features: ['24時間営業', '中央通り直近', '00分/30分開始混在', '個人練習Web受付'],
  },
  {
    id: 'noah-ochanomizu',
    name: 'サウンドスタジオノア 御茶ノ水店',
    chainName: 'SOUND STUDIO NOAH',
    area: '秋葉原・上野',
    nearestStation: '御茶ノ水駅 御茶ノ水橋口 徒歩3分 / 神保町駅 A5出口 徒歩5分',
    address: '東京都千代田区神田駿河台2丁目1-17',
    roomCount: 11,
    syncType: 'web_api',
    syncLabel: 'Web空き状況',
    systemName: 'ノア公式API連携',
    is24Hours: true,
    businessHours: '24時間営業',
    tel: '03-6427-3361',
    websiteUrl: 'https://www.studionoah.jp/ochanomizu/',
    features: ['24時間営業', '明大通り沿い', '00分/30分開始混在', '個人練習Web受付', '駅チカ徒歩3分'],
  },
  {
    id: 'bot-akiba-01',
    name: 'ベースオントップ 秋葉原昭和通り口店',
    chainName: 'BASS ON TOP',
    area: '秋葉原・上野',
    nearestStation: '秋葉原駅 昭和通り口 徒歩2分',
    address: '東京都千代田区神田佐久間町3-37-1',
    roomCount: 8,
    syncType: 'web_calendar',
    syncLabel: 'Web空き状況',
    systemName: 'スタジオルAPI連携',
    is24Hours: false,
    businessHours: '10:00〜24:00 (平日), 09:00〜24:00 (土日祝)',
    tel: '03-5829-9944',
    websiteUrl: 'https://bassontop.tokyo.jp/band/akihabara/',
    features: ['昭和通り口徒歩2分', '全室完全00分スタート', 'ピアノ常設室あり', '充実の設備'],
  },
  {
    id: 'gm-akiba-01',
    name: 'STUDIO GOODMAN AKIBA',
    chainName: 'STUDIO GOODMAN',
    area: '秋葉原・上野',
    nearestStation: '秋葉原駅 昭和通り口 徒歩5分 / 岩本町駅 徒歩3分',
    address: '東京都千代田区神田佐久間町3-21-7 熊谷ビルB1F-3F',
    roomCount: 11,
    syncType: 'web_calendar',
    syncLabel: 'Web空き状況',
    systemName: 'Reserve1.jp (自動巡回)',
    is24Hours: false,
    businessHours: '10:00〜24:00',
    tel: '03-3862-9010',
    websiteUrl: 'https://studio.goodman2020.com/',
    features: ['老舗ライブハウス併設', '全室00分スタート', '個人練習前日予約可能', '名機アンプ多数'],
  },
  {
    id: 'og-akiba-01',
    name: 'スタジオ音楽館 アキバ店',
    chainName: 'スタジオ音楽館',
    area: '秋葉原・上野',
    nearestStation: '秋葉原駅 電気街口 徒歩3分',
    address: '東京都千代田区外神田1-3-13 大森ビル3F-5F',
    roomCount: 7,
    syncType: 'web_calendar',
    syncLabel: 'Web空き状況',
    systemName: 'ajg.jp (自動巡回)',
    is24Hours: false,
    businessHours: '10:00〜24:00',
    tel: '03-3255-0810',
    websiteUrl: 'http://www.st-ongakukan.com/akihabara/akihabara.html',
    features: ['電気街口徒歩3分', '50帖大型Music Innあり', '個人練習21時受付', 'リーズナブルな料金'],
  },
  {
    id: 'ensemble-ueno',
    name: '音楽スタジオ ensemble',
    chainName: 'ensemble',
    area: '秋葉原・上野',
    nearestStation: 'JR上野駅 入谷口 徒歩3分',
    address: '東京都台東区東上野4-10-5 下条ビル3F',
    roomCount: 4,
    syncType: 'web_calendar',
    syncLabel: 'Web空き状況',
    systemName: 's-ens.net (自動巡回)',
    is24Hours: false,
    businessHours: '10:00〜23:00（10-17時は予約時営業）、月曜定休',
    tel: '03-3841-2904',
    websiteUrl: 'https://s-ens.net',
    features: ['上野駅徒歩3分', 'Aスタジオはアップライトピアノ常設', '入会金・年会費無料', '会員登録不要'],
  },
  {
    id: 'hmvp-otemachi',
    name: 'HMVP大手町スタジオ',
    chainName: 'HMVP',
    area: '秋葉原・上野',
    nearestStation: '東京メトロ大手町駅 A1出口 徒歩3分',
    address: '東京都千代田区内神田1-7-1 鎌倉橋ビルB2',
    roomCount: 1,
    syncType: 'web_calendar',
    syncLabel: 'Web空き状況',
    systemName: 'hmvp.net (自動巡回)',
    is24Hours: false,
    businessHours: '10:00〜22:00',
    tel: '03-5283-1475',
    websiteUrl: 'https://www.hmvp.net/studio/',
    features: ['ビッグバンドジャズ17名収容可(約30畳)', 'グランドピアノ・ウッドベース・ドラム常設', '最少2時間〜、平日10-18時は個人利用プランあり'],
  },
  {
    id: 'hmvp-shinokachimachi',
    name: 'HMVP新御徒町スタジオ',
    chainName: 'HMVP',
    area: '秋葉原・上野',
    nearestStation: '都営大江戸線/つくばエクスプレス 新御徒町駅 A4出口 徒歩1分',
    address: '東京都台東区小島2-19-16 FK21ビルB1',
    roomCount: 1,
    syncType: 'web_calendar',
    syncLabel: 'Web空き状況',
    systemName: 'hmvp.net (自動巡回)',
    is24Hours: false,
    businessHours: '10:00〜22:00',
    tel: '03-5283-1475',
    websiteUrl: 'https://www.hmvp.net/studio/shinokachi_studio.html',
    features: ['ビッグバンドジャズ17名収容可(約35畳)', 'グランドピアノ・ウッドベース・ドラム常設', '最少2時間〜、新御徒町駅徒歩1分'],
  },
  {
    id: 'node-suidobashi',
    name: 'スタジオノード 水道橋店',
    chainName: 'STUDIO NODE',
    area: '秋葉原・上野',
    nearestStation: 'JR総武線 水道橋駅西口 徒歩1分',
    address: '東京都千代田区神田三崎町3-7-5',
    roomCount: 12,
    syncType: 'web_calendar',
    syncLabel: 'Web空き状況',
    systemName: 'studio-node.jp (自動巡回)',
    is24Hours: false,
    businessHours: '10:00〜23:00（30分スタート室は10:30〜22:30）',
    tel: '03-3230-4646',
    websiteUrl: 'https://www.studio-node.com/HomeS.html',
    features: ['水道橋駅西口徒歩1分', '全12部屋', 'セルフレコーディング room(Vocal Booth付き)あり', '00分/30分開始混在'],
  },

  // -------------------------------------------------------------
  // 高田馬場エリア (5店舗 / 計53部屋)
  // -------------------------------------------------------------
  {
    id: 'noah-takadanobaba',
    name: 'サウンドスタジオノア 高田馬場店',
    chainName: 'SOUND STUDIO NOAH',
    area: '高田馬場',
    nearestStation: '高田馬場駅 徒歩3分',
    address: '東京都豊島区高田3-15-7',
    roomCount: 15,
    syncType: 'web_api',
    syncLabel: 'Web空き状況',
    systemName: 'ノア公式API連携',
    is24Hours: true,
    businessHours: '24時間営業',
    tel: '03-3985-6761',
    websiteUrl: 'https://www.studionoah.jp/baba/',
    features: ['24時間営業', '駅徒歩3分', '00分/30分開始混在', '個人練習Web受付'],
  },
  {
    id: 'gateway-takadanobaba-3rd',
    name: 'ゲートウェイスタジオ 高田馬場3号店',
    chainName: 'GATEWAY STUDIO',
    area: '高田馬場',
    nearestStation: '高田馬場駅 徒歩3分',
    address: '東京都新宿区高田馬場1-28-6 和光ビルB棟',
    roomCount: 15,
    syncType: 'web_calendar',
    syncLabel: 'Web空き状況',
    systemName: 'Reserve1.jp (自動巡回)',
    is24Hours: false,
    businessHours: '10:00〜23:00',
    tel: '03-3200-9997',
    websiteUrl: 'http://www.gw-studio.com/studios/studio_baba3rd/index',
    features: ['都内最大級15部屋', '00分/15分/30分/45分開始混在', 'ツインドラム完備室あり', '学割10%'],
  },
  {
    id: 'ongakukan-takadanobaba',
    name: 'スタジオ音楽館 馬場駅前店',
    chainName: 'スタジオ音楽館',
    area: '高田馬場',
    nearestStation: '高田馬場駅 徒歩1分',
    address: '東京都新宿区高田馬場1丁目34-8大輝ビル地下1階',
    roomCount: 6,
    syncType: 'web_calendar',
    syncLabel: 'Web空き状況',
    systemName: 'ajg.jp (自動巡回)',
    is24Hours: false,
    businessHours: '13:00〜22:00 (予約に応じ24時間対応可)',
    tel: '03-6278-9288',
    websiteUrl: 'http://www.st-ongakukan.com/takadanobabaekimae/takadanobabaekimae.html',
    features: ['駅一番近い徒歩1分', '23畳スタジオライブ対応', '個人練習前日21時〜', '格安料金体系'],
  },
  {
    id: 'bot-takadanobaba',
    name: 'ベースオントップ 高田馬場店',
    chainName: 'BASS ON TOP',
    area: '高田馬場',
    nearestStation: '高田馬場駅 戸山口 徒歩1分',
    address: '東京都新宿区高田馬場1-33-14 サンフラワービル4F',
    roomCount: 11,
    syncType: 'web_calendar',
    syncLabel: 'Web空き状況',
    systemName: 'スタジオル連携',
    is24Hours: true,
    businessHours: '24時間営業（年末年始は除く）',
    tel: '03-3203-9502',
    websiteUrl: 'https://www.bassontop.co.jp/band/takadanobaba/',
    features: ['駅徒歩1分', '24時間営業', '独立モニター完備室あり', '00分/30分開始混在'],
  },
  {
    id: 'bazooka-takadanobaba',
    name: 'BAZOOKA STUDIO',
    chainName: 'BAZOOKA STUDIO',
    area: '高田馬場',
    nearestStation: '高田馬場駅 徒歩2分',
    address: '東京都新宿区高田馬場3-3-3 三優ビルB1F',
    roomCount: 6,
    syncType: 'phone',
    syncLabel: '要事前会員登録（Web/電話予約）',
    systemName: 'ReserveMart (会員限定・自動巡回非対応)',
    is24Hours: false,
    businessHours: '要問い合わせ（深夜リハーサルは電話予約）',
    tel: '03-3360-3377',
    websiteUrl: 'https://bazookastudio.com/',
    features: ['駅徒歩2分', 'NATAL/CANOPUSドラム常設', 'レコーディング3部屋も併設', 'Web予約は要会員登録'],
  },

  // -------------------------------------------------------------
  // 池袋エリア (6店舗 / 計51部屋)
  // -------------------------------------------------------------
  {
    id: 'noah-ikebukuro',
    name: 'サウンドスタジオノア 池袋店',
    chainName: 'SOUND STUDIO NOAH',
    area: '池袋',
    nearestStation: '池袋駅 徒歩5分',
    address: '東京都豊島区東池袋2-63-1',
    roomCount: 11,
    syncType: 'web_api',
    syncLabel: 'ノア公式APIリアルタイム連携',
    systemName: 'ノア公式API連携',
    is24Hours: true,
    businessHours: '24時間営業',
    tel: '03-5951-8400',
    websiteUrl: 'https://www.studionoah.jp/ikebukuro/',
    features: ['駅徒歩5分', '3ピース向けSst完備', '大型E1st+Sub(20帖)あり', 'ボーカルブース2室'],
  },
  {
    id: 'bot-ikebukuro',
    name: 'ベースオントップ 池袋西口店',
    chainName: 'BASS ON TOP',
    area: '池袋',
    nearestStation: '池袋駅 西口 徒歩3分',
    address: '東京都豊島区西池袋1-10-1 ISOビルB1F',
    roomCount: 7,
    syncType: 'web_calendar',
    syncLabel: 'スタジオルAPI連携',
    systemName: 'スタジオルAPI連携',
    is24Hours: true,
    businessHours: '24時間営業',
    tel: '03-5992-7720',
    websiteUrl: 'https://www.bassontop.co.jp/band/ikebukuro-nishiguchi/',
    features: ['西口徒歩3分', '2025年12月リニューアル', 'キーボード2台常設室あり', '00分/30分開始混在'],
  },
  {
    id: 'ikebukuro-penta-main',
    name: 'スタジオペンタ池袋店',
    chainName: 'STUDIO PENTA',
    area: '池袋',
    nearestStation: 'JR池袋駅 東口 徒歩5分',
    address: '東京都豊島区南池袋2-47-8',
    roomCount: 5,
    syncType: 'phone',
    syncLabel: '電話予約のみ',
    systemName: '電話受付',
    is24Hours: false,
    businessHours: '10:00〜24:00',
    tel: '03-3981-5540',
    websiteUrl: 'https://studiopenta.jp/rehearsal/ikebukuro/',
    features: ['池袋エリア最古参', '東口徒歩5分', 'ヴィンテージアンプ完備', '電話/店頭予約のみ'],
  },
  {
    id: 'ikebukuro-penta-hands',
    name: 'スタジオペンタ池袋ハンズサイド',
    chainName: 'STUDIO PENTA',
    area: '池袋',
    nearestStation: 'JR池袋駅 東口 徒歩5分',
    address: '東京都豊島区東池袋1-26-4',
    roomCount: 8,
    syncType: 'phone',
    syncLabel: '電話/LINE予約のみ',
    systemName: '電話・LINE受付',
    is24Hours: false,
    businessHours: '10:00〜24:00',
    tel: '03-3981-4436',
    websiteUrl: 'https://studiopenta.jp/rehearsal/hands/',
    features: ['全8部屋', '20帖の大型室あり', 'LINE予約対応', '電話/LINE/店頭予約のみ'],
  },
  {
    id: 'vivo-ikebukuro',
    name: 'Vivo Sound Studio',
    chainName: 'Vivo Sound Studio',
    area: '池袋',
    nearestStation: '池袋駅 西口 徒歩2分',
    address: '東京都豊島区池袋2-47-3 キウレイコンビルB1',
    roomCount: 4,
    syncType: 'phone',
    syncLabel: '電話/LINE予約のみ',
    systemName: '電話・LINE受付 (自動巡回非対応)',
    is24Hours: false,
    businessHours: '平日12:00〜24:00 / 土日祝10:00〜24:00',
    tel: '03-5391-3411',
    websiteUrl: 'https://vivo-studio.jp/',
    features: ['グランドピアノ常設室あり', 'アップライトピアノ常設室あり', 'レコーディングブース併設', '電話/LINE予約のみ'],
  },
  {
    id: 'gateway-ikebukuro-kitaguchi',
    name: 'ゲートウェイスタジオ 池袋北口店',
    chainName: 'GATEWAY STUDIO',
    area: '池袋',
    nearestStation: '池袋駅 北口 徒歩2分',
    address: '東京都豊島区西池袋1-43-7 福住ビル5F・6F',
    roomCount: 16,
    syncType: 'web_calendar',
    syncLabel: 'Web空き状況',
    systemName: 'Reserve1.jp (自動巡回)',
    is24Hours: false,
    businessHours: '月〜金・祝10:00〜23:00 / 土日9:30〜23:00',
    tel: '03-5396-1119',
    websiteUrl: 'https://www.gw-studio.com/studios/studio_iken/index',
    features: ['池袋地域最大級16部屋', '5F・6F 2フロア構成', '00分/30分開始混在', 'Subルーム(個人練習向け)あり'],
  },

  // -------------------------------------------------------------
  // 下北沢エリア (6店舗 / 計40部屋)
  // -------------------------------------------------------------
  {
    id: 'noah-shimokitazawa',
    name: 'サウンドスタジオノア 下北沢店',
    chainName: 'SOUND STUDIO NOAH',
    area: '下北沢',
    nearestStation: '下北沢駅 徒歩5分',
    address: '東京都世田谷区北沢3-20-17',
    roomCount: 16,
    syncType: 'web_api',
    syncLabel: 'ノア公式APIリアルタイム連携',
    systemName: 'ノア公式API連携',
    is24Hours: true,
    businessHours: '24時間営業',
    tel: '03-3466-0058',
    websiteUrl: 'https://www.studionoah.jp/shimokita/',
    features: ['24時間営業', '大型Cst(24帖)あり', 'セルフレコブース', '00分/30分開始混在'],
  },
  {
    id: 'andys-studio',
    name: "ANDY'S STUDIO",
    chainName: "ANDY'S STUDIO",
    area: '下北沢',
    nearestStation: '下北沢駅 徒歩5分',
    address: '東京都世田谷区代沢5-29-15 SYビル2F',
    roomCount: 2,
    syncType: 'web_calendar',
    syncLabel: 'Web空き状況',
    systemName: 'スタジオル (studi-ol.com)',
    is24Hours: false,
    businessHours: '11:00〜24:00',
    tel: '03-5432-3805',
    websiteUrl: 'http://www.andys.jp/',
    features: ['旧楽器店ANDY\'S MUSIC跡地', 'レコーディング対応', '個人練習は電話予約のみ'],
  },
  {
    id: 'standby-studio',
    name: 'STANDBY MUSIC STUDIO',
    chainName: 'STANDBY MUSIC STUDIO',
    area: '下北沢',
    nearestStation: '下北沢駅 徒歩1分',
    address: '東京都世田谷区北沢2丁目12-10 SSビル1階',
    roomCount: 4,
    syncType: 'web_calendar',
    syncLabel: 'Web空き状況',
    systemName: 'スタジオル (studi-ol.com)',
    is24Hours: false,
    businessHours: '10:00〜23:00',
    tel: '03-5481-7433',
    websiteUrl: 'https://standby-studio.com/',
    features: ['駅徒歩1分', '全室DYNACORD POWERMATE常設', 'SSL AWS-900レコーディングルーム併設(ELS)'],
  },
  {
    id: 'gourdisland-west-studio',
    name: 'ガードアイランドスタジオ 下北沢ウエスト店',
    chainName: 'Gourdisland Studio',
    area: '下北沢',
    nearestStation: '下北沢駅 西口 徒歩0分',
    address: '東京都世田谷区北沢2-23-10',
    roomCount: 6,
    syncType: 'web_calendar',
    syncLabel: 'Web空き状況',
    systemName: 'スタジオル (studi-ol.com)',
    is24Hours: true,
    businessHours: '24時間営業（予約なしの場合23:00閉店）',
    tel: '03-5430-3334',
    websiteUrl: 'http://gourdisland-music.jp/shimokitawest/',
    features: ['駅西口徒歩0分', '全室壁面ミラー付き', '10帖/12帖の6部屋'],
  },
  {
    id: 'gourdisland-south-studio',
    name: 'ガードアイランドスタジオ 下北沢南口店',
    chainName: 'Gourdisland Studio',
    area: '下北沢',
    nearestStation: '下北沢駅 徒歩2分',
    address: '東京都世田谷区北沢2-13-6 3F',
    roomCount: 6,
    syncType: 'web_calendar',
    syncLabel: 'Web空き状況',
    systemName: 'スタジオル (studi-ol.com)',
    is24Hours: false,
    businessHours: '平日10:00〜23:00 / 土日祝9:00〜22:00',
    tel: '03-3414-9833',
    websiteUrl: 'http://gourdisland-music.jp/shimokitazawa/',
    features: ['駅徒歩2分', '学割・早割あり', '9帖/12帖の6部屋'],
  },
  {
    id: 'studio-bayd-shimokitazawa',
    name: 'STUDIO BAYD 下北沢店',
    chainName: 'STUDIO BAYD',
    area: '下北沢',
    nearestStation: '下北沢駅 南西口 徒歩7分',
    address: '東京都世田谷区代沢5-8-14 岩城ビル地下1階',
    roomCount: 6,
    syncType: 'web_api',
    syncLabel: 'Web空き状況',
    systemName: 'WnSpaceMusic公開API連携 (自動巡回)',
    is24Hours: true,
    businessHours: '24時間営業（完全無人店舗）',
    tel: '',
    websiteUrl: 'https://wnspacemusic.jp/studios/7',
    features: ['24時間営業', '完全無人・スマホ予約でオートロック解錠', 'ピアノ常設(D/Est)', 'イベント/ライブ対応(Fスタ最大80名)'],
  },

  // -------------------------------------------------------------
  // 吉祥寺エリア (3店舗 / 計32部屋)
  // -------------------------------------------------------------
  {
    id: 'noah-kichijoji',
    name: 'サウンドスタジオノア 吉祥寺店',
    chainName: 'SOUND STUDIO NOAH',
    area: '吉祥寺',
    nearestStation: 'JR中央線・京王井の頭線 吉祥寺駅 徒歩5分',
    address: '東京都武蔵野市吉祥寺東町1-4-27-B1F',
    roomCount: 11,
    syncType: 'web_api',
    syncLabel: 'Web空き状況',
    systemName: 'ノア公式API連携',
    is24Hours: true,
    businessHours: '24時間営業',
    tel: '0422-23-1741',
    websiteUrl: 'https://www.studionoah.jp/kichijoji/',
    features: ['24時間営業', '駅徒歩5分', 'セルフレコ対応(GSst+Sub)', '00分/30分開始混在'],
  },
  {
    id: 'rinkydink-kichijoji-ores',
    name: 'リンキィディンク 吉祥寺スタジオORES',
    chainName: 'Rinky Dink Studio',
    area: '吉祥寺',
    nearestStation: 'JR中央線・京王井の頭線 吉祥寺駅 北口 徒歩2分',
    address: '東京都武蔵野市吉祥寺本町1-7-8 第一マーブルビル3F',
    roomCount: 7,
    syncType: 'phone',
    syncLabel: '電話予約スタジオ',
    systemName: '会員制オンライン予約 (要事前登録) / 電話受付',
    is24Hours: false,
    businessHours: '平日10:00〜23:00・土日祝9:00〜23:00',
    tel: '0422-20-2355',
    websiteUrl: 'https://rinky.info/studio/ores/',
    features: ['駅徒歩2分', 'ビッグバンド対応(Sst/6st)', 'ハイエンド機材(TAMA/Ampeg)'],
  },
  {
    id: 'penta-kichijoji',
    name: 'スタジオペンタ 吉祥寺店',
    chainName: 'STUDIO PENTA',
    area: '吉祥寺',
    nearestStation: 'JR中央線・京王井の頭線 吉祥寺駅 公園口 徒歩30秒',
    address: '東京都武蔵野市吉祥寺南町1-1-4',
    roomCount: 14,
    syncType: 'phone',
    syncLabel: '電話予約スタジオ',
    systemName: 'ワンタップ電話受付 (tel:) / LINE予約',
    is24Hours: true,
    businessHours: '24時間営業',
    tel: '0422-42-0765',
    websiteUrl: 'https://studiopenta.jp/rehearsal/south/',
    features: ['駅徒歩30秒', '全14スタジオ', 'LINE予約対応', '個人練習は平日1週間前から予約可'],
  },

  // -------------------------------------------------------------
  // 高円寺エリア (7店舗 / 計30部屋)
  // -------------------------------------------------------------
  {
    id: 'sound-studio-dom',
    name: 'Sound Studio DOM',
    chainName: 'Sound Studio DOM',
    area: '高円寺',
    nearestStation: '高円寺駅 徒歩1分',
    address: '東京都杉並区高円寺南4-25-7 五明堂駅前ビル3F',
    roomCount: 3,
    syncType: 'web_calendar',
    syncLabel: 'Web空き状況',
    systemName: 'studi-ol.com (自動巡回)',
    is24Hours: true,
    businessHours: '24時間営業（0時〜14時は無人営業）',
    tel: '03-3318-3569',
    websiteUrl: 'https://soundstudiodom.com/',
    features: ['駅徒歩1分', 'イベントスペース併設', '1994年創業の老舗'],
  },
  {
    id: 'pig-studio',
    name: 'P.I.G.Studio',
    chainName: 'P.I.G.Studio',
    area: '高円寺',
    nearestStation: '高円寺駅 徒歩3分',
    address: '東京都杉並区高円寺北2-2-1 巳善ビル B1階',
    roomCount: 5,
    syncType: 'web_calendar',
    syncLabel: 'Web空き状況',
    systemName: 'studi-ol.com (自動巡回)',
    is24Hours: true,
    businessHours: '24時間営業・年中無休（完全無人）',
    tel: '03-3310-9311',
    websiteUrl: 'https://pig-studio.info/',
    features: ['24時間営業', 'セルフレジ決済', 'レコーディング対応(Est)', '学割対応(Cst)'],
  },
  {
    id: 'sonic-band-studio',
    name: 'SONIC BAND STUDIO',
    chainName: 'SONIC BAND STUDIO',
    area: '高円寺',
    nearestStation: 'JR高円寺駅 北口 徒歩7分',
    address: '東京都杉並区高円寺北',
    roomCount: 3,
    syncType: 'web_calendar',
    syncLabel: 'Web空き状況',
    systemName: 'studi-ol.com (自動巡回)',
    is24Hours: false,
    businessHours: '10:00〜24:00',
    tel: '03-3223-1009',
    websiteUrl: 'https://sonicbandstudio.com/pc/',
    features: ['全室同一料金', 'レコーディングスタジオ併設', '無料マイクレンタル'],
  },
  {
    id: 'koyama-main',
    name: 'スタジオ・コヤーマ本店',
    chainName: 'スタジオ・コヤーマ',
    area: '高円寺',
    nearestStation: '高円寺駅 北口',
    address: '東京都杉並区高円寺北2-18-7 千恵ビルB1',
    roomCount: 5,
    syncType: 'web_calendar',
    syncLabel: 'Web空き状況',
    systemName: 'studi-ol.com (自動巡回)',
    is24Hours: false,
    businessHours: '10:00〜24:00',
    tel: '03-5373-8248',
    websiteUrl: 'https://s-kym.com/',
    features: ['ネット予約5%割引', 'コントロールルーム併設', '常設電子ピアノ(Ast/Cst)'],
  },
  {
    id: 'koyama-r',
    name: 'スタジオ・コヤーマR店',
    chainName: 'スタジオ・コヤーマ',
    area: '高円寺',
    nearestStation: '高円寺駅 北口',
    address: '東京都杉並区高円寺北2-21-1 リリーベル高円寺スクエアB1',
    roomCount: 6,
    syncType: 'web_calendar',
    syncLabel: 'Web空き状況',
    systemName: 'studi-ol.com (自動巡回)',
    is24Hours: false,
    businessHours: '10:00〜24:00（無人営業・ネット予約限定）',
    tel: '03-5373-8248',
    websiteUrl: 'https://s-kym.com/',
    features: ['ネット予約限定', 'ピアノルーム(アップライト)', 'レッスンルーム併設'],
  },
  {
    id: 'musira',
    name: 'MUSIRA Studio',
    chainName: 'MUSIRA Studio',
    area: '高円寺',
    nearestStation: '新高円寺駅 すぐそば',
    address: '東京都杉並区高円寺南3-1-4 キングスコート2 B1F',
    roomCount: 3,
    syncType: 'web_calendar',
    syncLabel: 'Web空き状況',
    systemName: 'studi-ol.com (自動巡回)',
    is24Hours: true,
    businessHours: '平日15:00〜翌15:00 / 土日祝10:00〜翌10:00（一部時間帯は無人）',
    tel: '03-3316-3061',
    websiteUrl: 'https://musira.jp/',
    features: ['深夜早朝営業対応', '常設アップライトピアノ(Aスタ)', '録音・録画サービス'],
  },
  {
    id: 'studio-bayd-koenji',
    name: 'STUDIO BAYD 高円寺店',
    chainName: 'STUDIO BAYD',
    area: '高円寺',
    nearestStation: '高円寺駅 徒歩3分',
    address: '東京都杉並区高円寺南4-30-4 高円寺Kyテラス地下1階',
    roomCount: 5,
    syncType: 'web_api',
    syncLabel: 'Web空き状況',
    systemName: 'WnSpaceMusic公開API連携 (自動巡回)',
    is24Hours: true,
    businessHours: '24時間営業（完全無人店舗）',
    tel: '',
    websiteUrl: 'https://wnspacemusic.jp/studios/9',
    features: ['24時間営業', '完全無人・スマホ予約でオートロック解錠', 'イベント/ライブ対応(Aスタ最大60名)'],
  },

  // -------------------------------------------------------------
  // 船橋エリア (2店舗 / 計17部屋)
  // -------------------------------------------------------------
  {
    id: 'studiosun-nishifunabashi',
    name: 'STUDIO SUN 西船橋店',
    chainName: 'STUDIO SUN',
    area: '船橋',
    nearestStation: 'JR西船橋駅 南口 徒歩3分',
    address: '千葉県船橋市印内町570-1 鎌倉ビル1F',
    roomCount: 7,
    syncType: 'web_calendar',
    syncLabel: 'Web空き状況',
    systemName: 'webtoru.com (自動巡回)',
    is24Hours: false,
    businessHours: '9:00〜24:00（無人時間帯は6:00〜9:00も一部利用可）',
    tel: '047-431-9753',
    websiteUrl: 'https://studiosun1987.com/',
    features: ['駅徒歩3分', '無料駐車場10台完備', '00分/30分開始混在'],
  },
  {
    id: 'packs-funabashi',
    name: 'スタジオパックス船橋店',
    chainName: 'sound studio PACKS',
    area: '船橋',
    nearestStation: 'JR総武線 船橋駅 徒歩5分 / 京成本線 京成船橋駅 徒歩3分',
    address: '千葉県船橋市本町3-2-2 丸善ビル2F',
    roomCount: 10,
    syncType: 'phone',
    syncLabel: '電話予約スタジオ',
    systemName: '会員制オンライン予約 (要事前登録) / 初回電話受付',
    is24Hours: true,
    businessHours: '24時間営業・年中無休',
    tel: '047-425-5833',
    websiteUrl: 'https://www.studio-packs.jp/funabashi',
    features: ['24時間営業', '音楽スタジオ10部屋＋ダンススタジオ2部屋の大型施設', '学割対応'],
  },

  // -------------------------------------------------------------
  // 横浜エリア (3店舗 / 計21部屋)
  // -------------------------------------------------------------
  {
    id: 'penta-yokohama',
    name: 'スタジオペンタ横浜店',
    chainName: 'STUDIO PENTA',
    area: '横浜',
    nearestStation: 'JR横浜駅西口 徒歩5分',
    address: '神奈川県横浜市西区南幸2-8-9',
    roomCount: 6,
    syncType: 'phone',
    syncLabel: '電話予約スタジオ',
    systemName: '電話・LINE・店頭受付 (オンライン予約非対応)',
    is24Hours: true,
    businessHours: '24時間営業（基本営業時間10:00〜24:00）',
    tel: '045-313-3399',
    websiteUrl: 'https://studiopenta.jp/rehearsal/yokohama/',
    features: ['駅徒歩5分', '全6スタジオ個性的な機材構成', 'エンジニア付き本格Rec対応'],
  },
  {
    id: 'cloud9-yokohama-kitaguchi',
    name: 'クラウドナインスタジオ 横浜北口店',
    chainName: 'クラウドナインスタジオ',
    area: '横浜',
    nearestStation: '各線横浜駅 きた西口 徒歩5分',
    address: '神奈川県横浜市',
    roomCount: 11,
    syncType: 'web_api',
    syncLabel: 'Web空き状況',
    systemName: 'cloud9-web.jp公開API連携 (自動巡回)',
    is24Hours: false,
    businessHours: '平日10:00〜 / 土日祝9:00〜（最大翌朝6:30まで）',
    tel: '045-624-9499',
    websiteUrl: 'https://www.cloud-9-studio.com/studio/yokohama_n.html',
    features: ['駅徒歩5分', '音楽スタジオ11部屋＋ダンススタジオ1部屋', '00分/15分/30分開始混在'],
  },
  {
    id: 'yokohama-saila',
    name: 'ヨコハマ・セーラスタジオ',
    chainName: 'ヨコハマセーラスタジオ',
    area: '横浜',
    nearestStation: '桜木町駅 徒歩3分',
    address: '神奈川県横浜市',
    roomCount: 4,
    syncType: 'web_calendar',
    syncLabel: 'Web空き状況',
    systemName: 'Reserve1.jp (自動巡回)',
    is24Hours: false,
    businessHours: '9:00〜24:00',
    tel: '045-201-4988',
    websiteUrl: 'https://saila-s.jp/',
    features: ['バンド会員はネット予約可', 'レコーディング対応(Bst)', '個人練習・深夜は電話予約のみ'],
  },

  // -------------------------------------------------------------
  // 亀戸・小岩エリア (3店舗 / 計21部屋)
  // -------------------------------------------------------------
  {
    id: 'studio-divo-kameido',
    name: 'Studio DIVO 亀戸',
    chainName: 'Studio DIVO',
    area: '亀戸・小岩',
    nearestStation: 'JR亀戸駅 徒歩4分',
    address: '東京都江東区亀戸1-34-11',
    roomCount: 5,
    syncType: 'web_calendar',
    syncLabel: 'Web空き状況',
    systemName: 'webtoru.com (自動巡回)',
    is24Hours: false,
    businessHours: '月火水土日14:00〜22:00 / 木13:00〜22:00 / 金13:00〜23:00',
    tel: '03-5858-9197',
    websiteUrl: 'https://studio-divo.com/',
    features: ['駅徒歩4分', 'レコーディング併設(D-Lab)', '楽器レンタル無料'],
  },
  {
    id: 'studio-2times',
    name: 'Studio 2Times',
    chainName: 'Studio 2Times',
    area: '亀戸・小岩',
    nearestStation: 'JR小岩駅 南口 徒歩4分',
    address: '東京都江戸川区南小岩8丁目10-2',
    roomCount: 4,
    syncType: 'web_calendar',
    syncLabel: 'Web空き状況',
    systemName: 'studi-ol.com (自動巡回)',
    is24Hours: false,
    businessHours: '12:00〜24:00（時間外は電話・店頭のみ）',
    tel: '03-3672-8607',
    websiteUrl: 'https://studio2times.fc2.page/',
    features: ['駅徒歩4分', 'セルフレコーディング対応', '喫煙可'],
  },
  {
    id: 'soundstudio-m-koiwa',
    name: 'SOUND STUDIO M 小岩店',
    chainName: 'SOUND STUDIO M',
    area: '亀戸・小岩',
    nearestStation: 'JR小岩駅 北口 徒歩3分',
    address: '東京都江戸川区西小岩1-27-16 オルフェウスビル3〜4F',
    roomCount: 12,
    syncType: 'web_calendar',
    syncLabel: 'Web空き状況',
    systemName: 'orpheusrecords.info (自動巡回)',
    is24Hours: true,
    businessHours: '有人：平日12:00〜23:00・土日祝9:00〜23:00 / 無人：深夜〜早朝',
    tel: '03-3672-6316',
    websiteUrl: 'https://orpheusrecords.jp/ssm/koiwa/',
    features: ['駅徒歩3分', '全12部屋の大型施設', '深夜・早朝はスマートロック無人営業'],
  },

  // -------------------------------------------------------------
  // 松戸・柏エリア (5店舗 / 計36部屋)
  // -------------------------------------------------------------
  {
    id: 'musicbank-matsudo',
    name: '伊藤楽器 MUSIC BANK 松戸',
    chainName: '伊藤楽器 MUSIC BANK',
    area: '松戸・柏',
    nearestStation: 'JR松戸駅 東口 徒歩1分',
    address: '千葉県松戸市松戸1174-1',
    roomCount: 12,
    syncType: 'web_calendar',
    syncLabel: 'Web空き状況',
    systemName: 'studi-ol.com (自動巡回)',
    is24Hours: false,
    businessHours: '平日11:00〜20:00 / 土日祝10:00〜19:00',
    tel: '047-368-1161',
    websiteUrl: 'https://www.ito-ongaku.com/rental/musicbank-matsudo/',
    features: ['駅徒歩1分', 'バンドスタジオ3室＋練習室9室の大型施設', 'グランド/アップライトピアノ常設室あり'],
  },
  {
    id: 'studio-dugout2-matsudo',
    name: 'スタジオ ダグアウト2',
    chainName: 'スタジオ ダグアウト',
    area: '松戸・柏',
    nearestStation: 'JR松戸駅 西口 徒歩5分',
    address: '千葉県松戸市根本6-5 2F',
    roomCount: 7,
    syncType: 'web_calendar',
    syncLabel: 'Web空き状況',
    systemName: 'webtoru.com (自動巡回)',
    is24Hours: false,
    businessHours: '平日12:00〜24:00 / 土日祝10:00〜24:00',
    tel: '04-7718-2633',
    websiteUrl: 'https://www.studiodugout2.com/',
    features: ['駅徒歩5分', '天井高3500mmの開放的な空間', '全7部屋'],
  },
  {
    id: 'packs-shinmatsudo',
    name: 'サウンドスタジオパックス 新松戸店',
    chainName: 'sound studio PACKS',
    area: '松戸・柏',
    nearestStation: 'JR新松戸駅 徒歩3分',
    address: '千葉県松戸市新松戸4-14-2 KARAFUビル2F',
    roomCount: 5,
    syncType: 'phone',
    syncLabel: '電話予約スタジオ',
    systemName: '会員制オンライン予約 (要事前登録) / 初回電話受付',
    is24Hours: true,
    businessHours: '24時間営業・年中無休',
    tel: '047-711-5002',
    websiteUrl: 'https://www.studio-packs.jp/shinmatsudo',
    features: ['24時間営業', 'グランドピアノ常設室あり', 'ダンススタジオ2部屋併設'],
  },
  {
    id: 'gateway-kashiwa',
    name: 'ゲートウェイスタジオ 柏店',
    chainName: 'GATEWAY STUDIO',
    area: '松戸・柏',
    nearestStation: '柏駅 西口 徒歩2分',
    address: '千葉県柏市旭町1-2-1 第11関口ビルB1',
    roomCount: 7,
    syncType: 'web_calendar',
    syncLabel: 'Web空き状況',
    systemName: 'Reserve1.jp (自動巡回)',
    is24Hours: false,
    businessHours: '平日10:00〜23:00 / 土日祝9:00〜23:00',
    tel: '04-7144-9993',
    websiteUrl: 'http://www.gw-studio.com/studios/studio_kashi/index',
    features: ['駅徒歩2分', '入会金・年会費無料', '学割10%OFF対応'],
  },
  {
    id: 'soundstudio-m-kashiwa',
    name: 'SOUND STUDIO M 柏店',
    chainName: 'SOUND STUDIO M',
    area: '松戸・柏',
    nearestStation: 'JR柏駅 東口 徒歩10分',
    address: '千葉県柏市泉町16-30 大東ビル3F',
    roomCount: 5,
    syncType: 'web_calendar',
    syncLabel: 'Web空き状況',
    systemName: 'orpheusrecords.info (自動巡回)',
    is24Hours: false,
    businessHours: '平日12:00〜23:00 / 土日祝10:00〜23:00',
    tel: '04-7164-9413',
    websiteUrl: 'https://orpheusrecords.jp/ssm/kashiwa/',
    features: ['駅徒歩10分', 'ボーカルブース利用可(Bst)', '20時以降は無料駐車場あり'],
  },

  // -------------------------------------------------------------
  // 町田エリア (3店舗 / 計38部屋)
  // -------------------------------------------------------------
  {
    id: 'cloud9-machida',
    name: 'クラウドナインスタジオ 町田店',
    chainName: 'クラウドナインスタジオ',
    area: '町田',
    nearestStation: '小田急線・JR町田駅 徒歩3分',
    address: '東京都町田市原町田4-11-14 コロンブスビル6F',
    roomCount: 12,
    syncType: 'web_calendar',
    syncLabel: 'Web空き状況',
    systemName: 'cloud9-web.jp (自動巡回)',
    is24Hours: false,
    businessHours: '平日10:00〜 / 土日祝9:00〜（最大翌6:30まで）',
    tel: '042-721-9091',
    websiteUrl: 'https://www.cloud-9-studio.com/studio/machida.html',
    features: ['駅徒歩3分', 'グランドピアノ常設室2部屋', '全12部屋の大型施設'],
  },
  {
    id: 'gateway-machida',
    name: 'ゲートウェイスタジオ 町田店',
    chainName: 'GATEWAY STUDIO',
    area: '町田',
    nearestStation: 'JR町田駅 徒歩30秒',
    address: '神奈川県相模原市南区上鶴間本町3-17-3 アルファビル2F3F',
    roomCount: 12,
    syncType: 'web_calendar',
    syncLabel: 'Web空き状況',
    systemName: 'Reserve1.jp (自動巡回)',
    is24Hours: false,
    businessHours: '平日10:00〜23:00 / 土日祝10:00〜24:00',
    tel: '042-747-9990',
    websiteUrl: 'http://www.gw-studio.com/studios/studio_machi/index',
    features: ['駅徒歩30秒', '入会金・年会費無料', '学割10%OFF対応'],
  },
  {
    id: 'studioact-machida',
    name: 'スタジオアクト町田店',
    chainName: 'STUDIO ACT',
    area: '町田',
    nearestStation: '小田急線町田駅 徒歩5分 / JR町田駅 徒歩10分',
    address: '東京都町田市原町田6-29-10',
    roomCount: 14,
    syncType: 'web_calendar',
    syncLabel: 'Web空き状況',
    systemName: 'Reserve1.jp (自動巡回)',
    is24Hours: false,
    businessHours: '平日12:00〜24:00 / 土日祝9:00〜24:00',
    tel: '042-722-0005',
    websiteUrl: 'https://www.studioact.co.jp/',
    features: ['町田最大級の全14部屋', '2F/3F/B1Fの3フロア構成', 'ライブホール併設'],
  },
];

export const SUPPORTED_STUDIOS: SupportedStudio[] = ALL_SUPPORTED_STUDIOS.filter(
  (s) => !TEMP_HIDDEN_STUDIO_NAMES.includes(s.name)
);
