export interface SupportedStudio {
  id: string;
  name: string;
  chainName: string;
  area: '渋谷' | '新宿' | '秋葉原' | '高田馬場';
  nearestStation: string;
  address: string;
  roomCount: number;
  syncType: 'web_api' | 'web_calendar' | 'phone';
  syncLabel: string;
  systemName: string;
  is24Hours: boolean;
  businessHours: string;
  tel: string;
  websiteUrl: string;
  features: string[];
}

export const SUPPORTED_STUDIOS: SupportedStudio[] = [
  // -------------------------------------------------------------
  // 渋谷エリア (8店舗 / 計87部屋)
  // -------------------------------------------------------------
  {
    id: 'shibuya-noah-honten',
    name: 'サウンドスタジオノア 渋谷本店',
    chainName: 'SOUND STUDIO NOAH',
    area: '渋谷',
    nearestStation: '渋谷駅 ハチ公口 徒歩6分 / 神泉駅 徒歩8分',
    address: '東京都渋谷区宇田川町36-0 ビルディングB1F-4F',
    roomCount: 14,
    syncType: 'web_api',
    syncLabel: 'Web空き状況',
    systemName: 'ノア公式API連携',
    is24Hours: true,
    businessHours: '24時間営業',
    tel: '03-5485-1441',
    websiteUrl: 'https://www.studionoah.jp/shibuya_honten/',
    features: ['24時間営業', '大型リハ対応', '個人練習Web受付', 'セルフレコブース'],
  },
  {
    id: 'shibuya-noah-1',
    name: 'サウンドスタジオノア 渋谷1号店',
    chainName: 'SOUND STUDIO NOAH',
    area: '渋谷',
    nearestStation: '渋谷駅 東口・宮益坂 徒歩3分',
    address: '東京都渋谷区渋谷2-19-15 宮益坂ビルディングB1F',
    roomCount: 12,
    syncType: 'web_api',
    syncLabel: 'Web空き状況',
    systemName: 'ノア公式API連携',
    is24Hours: true,
    businessHours: '24時間営業',
    tel: '03-5485-1441',
    websiteUrl: 'https://www.studionoah.jp/shibuya1/',
    features: ['24時間営業', '駅チカ徒歩3分', '個人練習Web受付', 'JC-120/Marshall全室'],
  },
  {
    id: 'shibuya-noah-2',
    name: 'サウンドスタジオノア 渋谷2号店',
    chainName: 'SOUND STUDIO NOAH',
    area: '渋谷',
    nearestStation: '渋谷駅 ハチ公口 徒歩5分 / 井の頭通り沿い',
    address: '東京都渋谷区宇田川町39-2 B1F',
    roomCount: 14,
    syncType: 'web_api',
    syncLabel: 'Web空き状況',
    systemName: 'ノア公式API連携',
    is24Hours: true,
    businessHours: '24時間営業 (朝モーニング枠あり)',
    tel: '03-3780-5766',
    websiteUrl: 'https://www.studionoah.jp/shibuya2/',
    features: ['24時間営業', '朝割モーニング枠', '30分開始枠併用', '広々ロビー'],
  },
  {
    id: 'shibuya-noah-3',
    name: 'サウンドスタジオノア 渋谷3号店',
    chainName: 'SOUND STUDIO NOAH',
    area: '渋谷',
    nearestStation: '渋谷駅 西口・マークシティ口 徒歩5分',
    address: '東京都渋谷区道玄坂1-15-3 プリメーラ道玄坂B1F',
    roomCount: 15,
    syncType: 'web_api',
    syncLabel: 'Web空き状況',
    systemName: 'ノア公式API連携',
    is24Hours: true,
    businessHours: '24時間営業',
    tel: '03-6416-3663',
    websiteUrl: 'https://www.studionoah.jp/shibuya3/',
    features: ['24時間営業', '道玄坂エリア', '個人練習Web受付', '高音質PA'],
  },
  {
    id: 'shibuya-gateway',
    name: 'ゲートウェイスタジオ 渋谷道玄坂店',
    chainName: 'GATEWAY STUDIO',
    area: '渋谷',
    nearestStation: '渋谷駅 道玄坂口 徒歩4分',
    address: '東京都渋谷区道玄坂2-16-7 花菱ビル3F-5F',
    roomCount: 12,
    syncType: 'web_calendar',
    syncLabel: 'Web空き状況',
    systemName: 'Reserve1.jp (自動巡回)',
    is24Hours: true,
    businessHours: '24時間営業',
    tel: '03-3462-5552',
    websiteUrl: 'http://www.gw-studio.com/studio/st_shibuya.html',
    features: ['24時間営業', '00分/30分開始混在', '個人練習770円/h', '28帖ゲネプロスタジオ'],
  },
  {
    id: 'shibuya-penta-city',
    name: 'スタジオペンタ 渋谷シティサイド店',
    chainName: 'STUDIO PENTA',
    area: '渋谷',
    nearestStation: '渋谷駅 西口・桜丘町 徒歩3分',
    address: '東京都渋谷区桜丘町24-2 第3富士商事ビルB1F',
    roomCount: 7,
    syncType: 'phone',
    syncLabel: '電話予約スタジオ',
    systemName: 'ワンタップ電話受付 (tel:)',
    is24Hours: false,
    businessHours: '10:00〜24:00',
    tel: '03-3462-2811',
    websiteUrl: 'https://studiopenta.jp/rehearsal/shibuyacityside/',
    features: ['桜丘町徒歩3分', 'ワンタップ電話予約', '個人練習前日10時〜', 'ビンテージアンプ常設'],
  },
  {
    id: 'shibuya-penta-juke',
    name: 'スタジオペンタ 渋谷ジュークハウス店',
    chainName: 'STUDIO PENTA',
    area: '渋谷',
    nearestStation: '渋谷駅 西口 徒歩4分',
    address: '東京都渋谷区桜丘町15-17 登栄桜丘ビルB1F',
    roomCount: 7,
    syncType: 'phone',
    syncLabel: '電話予約スタジオ',
    systemName: 'ワンタップ電話受付 (tel:)',
    is24Hours: false,
    businessHours: '10:00〜24:00',
    tel: '03-3462-2815',
    websiteUrl: 'https://studiopenta.jp/rehearsal/shibuyajukehouse/',
    features: ['西口徒歩4分', 'ワンタップ電話予約', '個人練習前日10時〜', '名物スタッフ常駐'],
  },
  {
    id: 'shibuya-penta-moon',
    name: 'スタジオペンタ 渋谷ムーンサイド店',
    chainName: 'STUDIO PENTA',
    area: '渋谷',
    nearestStation: '渋谷駅 西口 徒歩5分',
    address: '東京都渋谷区桜丘町14-10 渋谷コープB1F',
    roomCount: 6,
    syncType: 'phone',
    syncLabel: '電話予約スタジオ',
    systemName: 'ワンタップ電話受付 (tel:)',
    is24Hours: false,
    businessHours: '10:00〜24:00',
    tel: '03-3462-2818',
    websiteUrl: 'https://studiopenta.jp/rehearsal/shibuyamoonside/',
    features: ['ワンタップ電話予約', '桜丘町静音環境', '個人練習前日10時〜', '丁寧な機材メンテ'],
  },

  // -------------------------------------------------------------
  // 新宿エリア (4店舗 / 計54部屋)
  // -------------------------------------------------------------
  {
    id: 'shinjuku-noah',
    name: 'サウンドスタジオノア 新宿店',
    chainName: 'SOUND STUDIO NOAH',
    area: '新宿',
    nearestStation: '新宿駅 西口 徒歩4分 / 新宿西口駅 徒歩3分',
    address: '東京都新宿区西新宿1-3-14 新宿サンゲンビル1F-7F',
    roomCount: 21,
    syncType: 'web_api',
    syncLabel: 'Web空き状況',
    systemName: 'ノア公式API連携',
    is24Hours: true,
    businessHours: '24時間営業',
    tel: '03-5332-8366',
    websiteUrl: 'https://www.studionoah.jp/shinjuku/',
    features: ['都内最大級21部屋', '24時間営業', '西口大ガードすぐ', 'グランドピアノ室完備'],
  },
  {
    id: 'shinjuku-node',
    name: 'STUDIO NODE 新宿店',
    chainName: 'STUDIO NODE',
    area: '新宿',
    nearestStation: '新宿駅 西口 徒歩6分 / 西武新宿駅 徒歩3分',
    address: '東京都新宿区西新宿7-16-12 YSビルB1F',
    roomCount: 7,
    syncType: 'web_calendar',
    syncLabel: 'Web空き状況',
    systemName: 'studio-node.jp (自動巡回)',
    is24Hours: false,
    businessHours: '10:00〜24:00',
    tel: '03-5386-3371',
    websiteUrl: 'https://www.studio-node.com/HomeSH.html',
    features: ['西新宿エリア', '00分/30分開始混在', 'Web予約即時完結', '手頃な料金設定', 'ドラム設備充実'],
  },
  {
    id: 'shinjuku-penta-main',
    name: 'スタジオペンタ 新宿店',
    chainName: 'STUDIO PENTA',
    area: '新宿',
    nearestStation: '新宿駅 東口 徒歩3分 / 新宿三丁目駅 徒歩2分',
    address: '東京都新宿区新宿3-11-6 エビスビルB1F',
    roomCount: 19,
    syncType: 'web_calendar',
    syncLabel: '土日祝Web / 平日電話',
    systemName: 'ペンタ新宿 空き室ボード連携',
    is24Hours: false,
    businessHours: '10:00〜24:00',
    tel: '03-3351-3140',
    websiteUrl: 'https://studiopenta.jp/rehearsal/shinjuku/',
    features: ['新宿東口屈指の19部屋', '土日祝Web空き状況公開', '平日ワンタップ電話予約', '個人練習前日10時〜'],
  },
  {
    id: 'ongakukan-shinjuku-west',
    name: 'スタジオ音楽館 新宿西口店',
    chainName: 'スタジオ音楽館',
    area: '新宿',
    nearestStation: '新宿駅 西口 徒歩2分 / 新宿西口駅 徒歩3分',
    address: '東京都新宿区西新宿7-15-4 YSビルB2F',
    roomCount: 7,
    syncType: 'web_calendar',
    syncLabel: 'Web空き状況',
    systemName: 'ajg.jp (自動巡回)',
    is24Hours: false,
    businessHours: '10:00〜24:00 (予約に応じ24時間営業対応)',
    tel: '03-3368-0131',
    websiteUrl: 'http://www.st-ongakukan.com/sinjukunishi/sinjukunishi.html',
    features: ['西新宿駅近徒歩2分', '全室00分スタート', 'Web即時空き状況確認', '個人練習前日21時〜', '格安料金体系'],
  },

  // -------------------------------------------------------------
  // 秋葉原エリア (5店舗 / 計51部屋)
  // -------------------------------------------------------------
  {
    id: 'akiba-noah',
    name: 'サウンドスタジオノア 秋葉原店',
    chainName: 'SOUND STUDIO NOAH',
    area: '秋葉原',
    nearestStation: '末広町駅 徒歩1分 / 秋葉原駅 徒歩6分',
    address: '東京都千代田区外神田6-14-8',
    roomCount: 14,
    syncType: 'web_api',
    syncLabel: 'Web空き状況',
    systemName: 'ノア公式API連携',
    is24Hours: true,
    businessHours: '24時間営業',
    tel: '03-5816-8383',
    websiteUrl: 'https://www.studionoah.jp/akihabara/',
    features: ['24時間営業', '中央通り直近', '00分/30分開始混在', '個人練習Web受付'],
  },
  {
    id: 'noah-ochanomizu',
    name: 'サウンドスタジオノア 御茶ノ水店',
    chainName: 'SOUND STUDIO NOAH',
    area: '秋葉原',
    nearestStation: '御茶ノ水駅 御茶ノ水橋口 徒歩3分 / 神保町駅 A5出口 徒歩5分',
    address: '東京都千代田区神田駿河台2丁目1-17',
    roomCount: 11,
    syncType: 'web_api',
    syncLabel: 'Web空き状況',
    systemName: 'ノア公式API連携',
    is24Hours: true,
    businessHours: '24時間営業',
    tel: '03-6427-3361',
    websiteUrl: 'https://www.studionoah.jp/ochanomizu/',
    features: ['24時間営業', '明大通り沿い', '00分/30分開始混在', '個人練習Web受付', '駅チカ徒歩3分'],
  },
  {
    id: 'akiba-bot',
    name: 'ベースオントップ 秋葉原昭和通り口店',
    chainName: 'BASS ON TOP',
    area: '秋葉原',
    nearestStation: '秋葉原駅 昭和通り口 徒歩2分',
    address: '東京都千代田区神田佐久間町3-37-1',
    roomCount: 8,
    syncType: 'web_calendar',
    syncLabel: 'Web空き状況',
    systemName: 'スタジオルAPI連携',
    is24Hours: false,
    businessHours: '10:00〜24:00 (平日), 09:00〜24:00 (土日祝)',
    tel: '03-5829-9944',
    websiteUrl: 'https://bassontop.tokyo.jp/studio/akihabara/',
    features: ['昭和通り口徒歩2分', '全室完全00分スタート', 'ピアノ常設室あり', '充実の設備'],
  },
  {
    id: 'akiba-goodman',
    name: 'STUDIO GOODMAN AKIBA',
    chainName: 'STUDIO GOODMAN',
    area: '秋葉原',
    nearestStation: '秋葉原駅 昭和通り口 徒歩5分 / 岩本町駅 徒歩3分',
    address: '東京都千代田区神田佐久間町3-21-7 熊谷ビルB1F-3F',
    roomCount: 11,
    syncType: 'web_calendar',
    syncLabel: 'Web空き状況',
    systemName: 'Reserve1.jp (自動巡回)',
    is24Hours: false,
    businessHours: '10:00〜24:00',
    tel: '03-3862-9010',
    websiteUrl: 'https://clubgoodman.com/studio.html',
    features: ['老舗ライブハウス併設', '全室00分スタート', '個人練習前日予約可能', '名機アンプ多数'],
  },
  {
    id: 'akiba-ongakukan',
    name: 'スタジオ音楽館 アキバ店',
    chainName: 'スタジオ音楽館',
    area: '秋葉原',
    nearestStation: '秋葉原駅 電気街口 徒歩3分',
    address: '東京都千代田区外神田1-3-13 大森ビル3F-5F',
    roomCount: 7,
    syncType: 'web_calendar',
    syncLabel: 'Web空き状況',
    systemName: 'ajg.jp (自動巡回)',
    is24Hours: false,
    businessHours: '10:00〜24:00',
    tel: '03-3255-0810',
    websiteUrl: 'https://www.studiocan.co.jp/akiba/',
    features: ['電気街口徒歩3分', '50帖大型Music Innあり', '個人練習21時受付', 'リーズナブルな料金'],
  },

  // -------------------------------------------------------------
  // 高田馬場エリア (5店舗 / 計53部屋)
  // -------------------------------------------------------------
  {
    id: 'noah-takadanobaba',
    name: 'サウンドスタジオノア 高田馬場店',
    chainName: 'SOUND STUDIO NOAH',
    area: '高田馬場',
    nearestStation: '高田馬場駅 徒歩3分',
    address: '東京都豊島区高田3-15-7',
    roomCount: 15,
    syncType: 'web_api',
    syncLabel: 'Web空き状況',
    systemName: 'ノア公式API連携',
    is24Hours: true,
    businessHours: '24時間営業',
    tel: '03-3985-6761',
    websiteUrl: 'https://www.studionoah.jp/baba/',
    features: ['24時間営業', '駅徒歩3分', '00分/30分開始混在', '個人練習Web受付'],
  },
  {
    id: 'gateway-takadanobaba-3rd',
    name: 'ゲートウェイスタジオ 高田馬場3号店',
    chainName: 'GATEWAY STUDIO',
    area: '高田馬場',
    nearestStation: '高田馬場駅 徒歩3分',
    address: '東京都新宿区高田馬場1-28-6 和光ビルB棟',
    roomCount: 15,
    syncType: 'web_calendar',
    syncLabel: 'Web空き状況',
    systemName: 'Reserve1.jp (自動巡回)',
    is24Hours: true,
    businessHours: '10:00〜23:00 (予約状況により24時間対応可)',
    tel: '03-3200-9997',
    websiteUrl: 'http://www.gw-studio.com/studios/studio_baba3rd/index',
    features: ['都内最大級15部屋', '00分/15分/30分/45分開始混在', 'ツインドラム完備室あり', '学割10%'],
  },
  {
    id: 'ongakukan-takadanobaba',
    name: 'スタジオ音楽館 馬場駅前店',
    chainName: 'スタジオ音楽館',
    area: '高田馬場',
    nearestStation: '高田馬場駅 徒歩1分',
    address: '東京都新宿区高田馬場1丁目34-8大輝ビル地下1階',
    roomCount: 6,
    syncType: 'web_calendar',
    syncLabel: 'Web空き状況',
    systemName: 'ajg.jp (自動巡回)',
    is24Hours: false,
    businessHours: '13:00〜22:00 (予約に応じ24時間対応可)',
    tel: '03-6278-9288',
    websiteUrl: 'http://www.st-ongakukan.com/takadanobabaekimae/takadanobabaekimae.html',
    features: ['駅一番近い徒歩1分', '23畳スタジオライブ対応', '個人練習前日21時〜', '格安料金体系'],
  },
  {
    id: 'bot-takadanobaba',
    name: 'ベースオントップ 高田馬場店',
    chainName: 'BASS ON TOP',
    area: '高田馬場',
    nearestStation: '高田馬場駅 戸山口 徒歩1分',
    address: '東京都新宿区高田馬場1-33-14 サンフラワービル4F',
    roomCount: 11,
    syncType: 'web_calendar',
    syncLabel: 'Web空き状況',
    systemName: 'スタジオル連携',
    is24Hours: true,
    businessHours: '24時間営業（年末年始は除く）',
    tel: '03-3203-9502',
    websiteUrl: 'https://www.bassontop.co.jp/band/takadanobaba/',
    features: ['駅徒歩1分', '24時間営業', '独立モニター完備室あり', '00分/30分開始混在'],
  },
  {
    id: 'bazooka-takadanobaba',
    name: 'BAZOOKA STUDIO',
    chainName: 'BAZOOKA STUDIO',
    area: '高田馬場',
    nearestStation: '高田馬場駅 徒歩2分',
    address: '東京都新宿区高田馬場3-3-3 三優ビルB1F',
    roomCount: 6,
    syncType: 'phone',
    syncLabel: '要事前会員登録（Web/電話予約）',
    systemName: 'ReserveMart (会員限定・自動巡回非対応)',
    is24Hours: false,
    businessHours: '要問い合わせ（深夜リハーサルは電話予約）',
    tel: '03-3360-3377',
    websiteUrl: 'https://bazookastudio.com/',
    features: ['駅徒歩2分', 'NATAL/CANOPUSドラム常設', 'レコーディング3部屋も併設', 'Web予約は要会員登録'],
  },
];
